### ISSUE TITLE
reconnect feature is unspported

### ISSUE THREAD

**Issue by KeyLD** [ZhangGe6/onnx-modifier#10]
for example:
a -> b
b -> c

I modified the output of node a to the input of node c, but it will not reconnect between a and c.

**Comment by ZhangGe6** [comment]
As is stated in the [readme](https://github.com/ZhangGe6/onnx-modifier#rename-the-name-of-node-inputsoutputs):
> Note: To link node $A$ (`data_0` in the above example) to node $B$ (the 1st `Conv` in the above example), **it is suggested to edit the input of node $B$ to the output of node `A`, rather than edit the output of node $A$ to the input of node `B`.** Because the input of $B$ can also be other node's output (`Transpose`  in the above example ) and unexpected results will happen.

You can try to rename the input of node c to the output of node a (rather than rename the output of node a to the input of node c ) and see whether it works.
