### ISSUE TITLE
exe的百度网盘链接失效了

### ISSUE THREAD

**Issue by ZJDATY** [ZhangGe6/onnx-modifier#100]
![image](https://github.com/ZhangGe6/onnx-modifier/assets/29767049/01c34025-cceb-4b13-b616-d246e7ab4682)
谷歌网盘里的还是去年的版本，可以新版本重新打包一份吗？

**Comment by ZhangGe6** [comment]
@ZJDATY 谢谢反馈！已经基于最新代码更新了可执行文件，readme中的下载链接也做了对应更新。
