### ISSUE TITLE
属性编辑的输入会自动丢失

### ISSUE THREAD

**Issue by wayen820** [ZhangGe6/onnx-modifier#107]
Uploading moya-2024-06-22.mp4…

首先非常感谢作者提供这么方便的工具.但是我发现在有些情形,如添加slice,有多个参数的时候,输入会自动丢失导致输入不进去.

**Comment by wayen820** [comment]
https://github.com/ZhangGe6/onnx-modifier/assets/23117916/58dab0b1-1144-46a5-987f-73f890b06fc5

**Comment by ZhangGe6** [comment]
@wayen820 问题收到，谢谢反馈。今天我来看一下。

**Comment by ZhangGe6** [comment]
@wayen820 哈喽，我提交了一个MR来修复该问题。烦请拉取最新代码，帮忙验证一下是否可以正常工作，感谢。
