### ISSUE TITLE
添加input后，onnxruntime出错 “'/input_0' is not a graph input”

### ISSUE THREAD

**Issue by charllll** [ZhangGe6/onnx-modifier#108]
![one_greater onnx](https://github.com/ZhangGe6/onnx-modifier/assets/29768383/3cd69dcf-0068-4f83-a1aa-45771efd2abb)

这是我从其他model上截取的，但是缺少了input，所以我在greater 之前添加了一个input。但是onnxruntime 运行显示

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Load model from modified_onnx/modified_one_greater.onnx failed:Invalid model. Node input '/input_0' is not a graph input, initializer, or output of a previous node.
```

非常感谢做出了这么棒的工具

**Comment by ZhangGe6** [comment]
@charllll 谢谢反馈。可否提供以下demo模型（在greater前增加input）时的状态，方便debug，谢谢。

**Comment by charllll** [comment]
[one_greater.onnx.zip](https://github.com/user-attachments/files/16006557/one_greater.onnx.zip)

run:
```
polygraphy run one_greater.onnx --onnxrt
```
dump python 文件，可以看到input=[]
```
python -m onnxconverter_common.onnx2py one_greater.onnx one_greater.py
```

**Comment by ZhangGe6** [comment]
@charllll 你好，问题无法复现。我这边add input可以正常推理得到输出。操作步骤为：
1. 点击“Greater”节点，在弹出的侧边栏中点击“Add Input”;
2. 在弹出的对话框中的shape一栏，输入“[4, 1, 6, 2500, 1]”，点击“Confirm”;
3. 点击“Download”，得到“modified_one_greater.onnx”

加载和执行：
```python
import numpy as np
import onnxruntime as ort

model_path = "./modified_one_greater.onnx"
session = ort.InferenceSession(model_path)

input_shape = (4, 1, 6, 2500, 1)
x = np.random.randn(*input_shape).astype(np.float32)

input_name = session.get_inputs()[0].name
outs = session.run(None, {input_name: x})
print(outs[0].shape) # (4, 1, 6, 2500, 1)
```
注意到初次comment提供的截图中，编辑后的模型输入名是“/input_0”。但如果只执行了Add Input操作的话，模型输入名应该是默认的”/Slice_7_output_0“。请问是否还进行了其他操作？可能是其他操作引入了问题。

**Comment by charllll** [comment]
先修改了greater input name （/Slice_7_output_0 -> /input_0），然后点击add input

**Comment by ZhangGe6** [comment]
@charllll 我提交了一个patch修复了该问题，可更新至最新代码看一下是否可以正常工作。谢谢反馈。

**Comment by charllll** [comment]
已经fix了，感谢！
