### ISSUE TITLE
Model Loading through file path 

### ISSUE THREAD

**Issue by abhigoku10** [ZhangGe6/onnx-modifier#111]
@ZhangGe6  thansk for sharing the awesome work !! i have few queries 
1. is there any way we can load the model from a file path instead of gui's open file dialog box ? 
2.  I tried to modify the source code with other libraries imports the web ui is crashing with giving any error , can you let us knw how to add it so that we can expand the existing code base with other features "const fs = require('fs'); "
Thanks in advances

**Comment by ZhangGe6** [comment]
@abhigoku10 Loading model from file path is not supported now. Can you share what the motivation/benefit is to do so?

**Comment by abhigoku10** [comment]
@ZhangGe6  thansk for the response , we are trying to add a model operations in python part of the existing code base where graph needs to be transfered from python to java module but we end having error at transfering and loading . Is there any option to do this functionality ?

**Comment by ZhangGe6** [comment]
@abhigoku10 Transfering data from Python to Java is not supported yet. I am not familiar with this field, so I am afraid I can't provide useful advice.
