### ISSUE TITLE
文件大小较大的模型的修改与保存有困难

### ISSUE THREAD

**Issue by LoonyReina** [ZhangGe6/onnx-modifier#114]
我在一个1.89g的模型上增加输入、删除节点等操作后，无法保存作品。
文件链接：
链接：https://pan.baidu.com/s/1kpf0lLIuYCQU6e3A0Ea_1w?pwd=mzyd 
提取码：mzyd

**Comment by LoonyReina** [comment]
现在的情况是，不涉及对输入输出节点的改动的作品可以保存，是否是我对输入输出增删操作有误？

**Comment by ZhangGe6** [comment]
@LoonyReina 谢谢反馈！“无法保存作品”时，请看一下终端是否打印了相关错误log？具体的操作和预期的操作是什么？方便复现。

**Comment by LoonyReina** [comment]
@ZhangGe6 您好，我这边具体问题是点击保存（download）后，应用界面没有反馈成功或失败，我查看了这个应用创建的默认文件夹路径，也没有文件。
关于终端的错误log，我没有留意（不熟练）。我的操作提供如下：通过修改scatterND节点输出把scatterND节点从模型断开
![图片1](https://github.com/user-attachments/assets/d7086caf-c66e-452a-8d8a-d023afaeeeb0)
把原本scatterND节点输出添加为模型输入
![图片2](https://github.com/user-attachments/assets/70cb0b92-05df-4971-9ec1-9c56319a8fc0)
然后保存（download）。
scatterND节点在模型这个位置
![图片3](https://github.com/user-attachments/assets/4df5f60c-6b4a-4446-b1fd-3529e9b7c6cb)

**Comment by ZhangGe6** [comment]
@LoonyReina 收到。百度网盘下载文件需要时间，问题复现/修复会在这里同步。

**Comment by ZhangGe6** [comment]
@LoonyReina 你好，不好意思久等了，今天下载好模型，本地复现了一下：是可以正常修改并保存的，但从download到成功保存模型，需要等待近30秒的时间。这是因为如果修改了input，或者增加ouput，会自动触发shape inference，这一步会花费一些时间，比较大的模型时间开销比较明显。

**Comment by LoonyReina** [comment]
@ZhangGe6 原来如此，谢谢你！
