### ISSUE TITLE
Add button not working

### ISSUE THREAD

**Issue by Jerry-Master** [ZhangGe6/onnx-modifier#115]
The add button is not working for GridSample and other operations. At the start of the app it is working fot nodes like abs or cos but then when trying to add other nodes it does not let you do it. The button stops working. Moreover, if you change to GridSample, click and then change to Abs it also does not work. It is like changing the node breaks the button permanently.

**Comment by ZhangGe6** [comment]
@Jerry-Master Thanks for the feedback and sorry for the late response. When some error happens, the app crashes and stops responding to users. However, adding node "GridSample" is expected to work. When using Chrome, it is suggested to enter the developer tool (click F12) and check the "Console" tab to check the error info.
