### ISSUE TITLE
请问在添加INPUT时，可以设置shape是动态的吗

### ISSUE THREAD

**Issue by Tyx-main** [ZhangGe6/onnx-modifier#118]
背景：
我需要拆分一个A.onnx 为 B.onnx和C.onnx， 其中 B.onnx的输出是C.onnx的输入， C.onnx的输入原本是动态的shape，请问在拆分出C.onnx并设置其输入INPUT的shape的时候，如何设置动态shape呢？
![image](https://github.com/user-attachments/assets/4611271c-1d3e-4947-9280-3b14fe35a023)

**Comment by ZhangGe6** [comment]
当前仅支持设定batch维度为动态，点击生成的C.onnx的inpu节点（如果没有input节点可以：点击Loop节点，在弹出的侧边栏中点击“Add Input”），然后点击“Set dynamic batch size”即可。
