### ISSUE TITLE
删除子分支后，分支上的节点变成了inputs。

### ISSUE THREAD

**Issue by ganleiboy** [ZhangGe6/onnx-modifier#12]
1，原始模型删除子分支，如下图：
![screenshot_24](https://user-images.githubusercontent.com/35066897/183435902-e58a199d-e9b5-422a-ba9d-a8324b4c31e9.png)

2，保存后打开修剪过的模型，可以看到inputs变多了，如下图：
![screenshot_25](https://user-images.githubusercontent.com/35066897/183436047-218cef28-351e-4855-9acc-58ddd0c1bf6f.png)

3，我是通过如下代码对模型的inputs进行了删除：
```python
import onnx                         

inputpath = "./descriptor.onnx"

# 1，修改模型
model = onnx.load(inputpath)
inputs = model.graph.input
inputs_num = 1  # 原始网络的输入会排在列表的最前面，所以调用pop函数删除冗余输入
for i in range(len(inputs)-inputs_num):
    inputs.pop()
print(inputs)

# 2，检查结构并保存模型（覆盖保存）
onnx.checker.check_model(model)
onnx.save(model, inputpath)
```

**Comment by William19971229** [comment]
你好，这个问题最近我在用的时候也发现了，正在尝试修复，谢谢详细的反馈和提供备选解决方案！

**Comment by ZhangGe6** [comment]
你好，这个问题最近我在用的时候也发现了，正尝试修复，谢谢详细的反馈和提供备选解决方案！

**Comment by ZhangGe6** [comment]
@ganleiboy 你好，我更新了一个版本来尝试解决这个问题，如果方便的话，请使用新版做修改试试，如果仍然存在问题，欢迎继续讨论~
