### ISSUE TITLE
Not work correct docker container

### ISSUE THREAD

**Issue by MohammadWolf95** [ZhangGe6/onnx-modifier#120]
**What do you want**
What is the editing goal? aka, what changes do you want to apply to your model?

**What did you do**
What steps did you take using `onnx-modifier`?

**What do you see**
If the editing result is not as expected, what is it? **It is also strongly recommended to share the error log in the console.**

**Model file to reproduce (optional)**
If possible, it is very grateful to share the ONNX model file, which can help find out the issue a lot.

**Additional context (optional)**

**Comment by ZhangGe6** [comment]
@MohammadWolf95 Thanks for reporting! The Dockfile has been updated.
