### ISSUE TITLE
网盘链接全部失效了

### ISSUE THREAD

**Issue by LiuChaoMi** [ZhangGe6/onnx-modifier#125]
**What do you want**
What is the editing goal? aka, what changes do you want to apply to your model?

**What did you do**
What steps did you take using `onnx-modifier`?

**What do you see**
If the editing result is not as expected, what is it? **It is also strongly recommended to share the error log in the console.**

**Model file to reproduce (optional)**
If possible, it is very grateful to share the ONNX model file, which can help find out the issue a lot.

**Additional context (optional)**

**Comment by ZhangGe6** [comment]
@LiuChaoMi 试了一下，是有效的呀。百度网盘：https://pan.baidu.com/s/1CDGCC5bzmRL4b0F60PANYg?from=init&pwd=vh32

**Comment by LiuChaoMi** [comment]
我网络的问题，抱歉
