### ISSUE TITLE
support feature "mark a tensor as  model output"

### ISSUE THREAD

**Issue by lordrebel** [ZhangGe6/onnx-modifier#13]
您好，
想问下可以支持选择一个node从的 输入或输出tensor 并把他标记成模型的输出吗？

**Comment by ZhangGe6** [comment]
你好，请问这个需求是否和[这里](https://github.com/ZhangGe6/onnx-modifier/issues/8#issuecomment-1171799733)提到的相同？如果是的话，它已经被加入了[todo list](https://github.com/ZhangGe6/onnx-modifier/blob/master/docs/todo_list.md)，不过暂时还不支持，您可以考虑手动调用ONNX Python API完成。

**Comment by lordrebel** [comment]
就是这个，谢谢～

**Comment by ZhangGe6** [comment]
@lordrebel 你好，现在已经支持增加模型输出节点啦，欢迎使用~，详情参见[readme](https://github.com/ZhangGe6/onnx-modifier/blob/master/readme_zh-CN.md#%E5%A2%9E%E5%8A%A0%E6%A8%A1%E5%9E%8B%E8%BE%93%E5%87%BA%E8%8A%82%E7%82%B9)。
