### ISSUE TITLE
can't download modified model

### ISSUE THREAD

**Issue by EnnSou** [ZhangGe6/onnx-modifier#14]
![Screenshot from 2022-09-07 16-18-58](https://user-images.githubusercontent.com/44028875/188827717-ee5489e6-8ccb-450b-b444-402bd9bd2bf9.png)
加载模型后点download按钮就会提示错误

**Comment by EnnSou** [comment]
通过 open model 选项打开的模型就ok，直接把model file 拖到网页会遇到这个问题。

**Comment by ZhangGe6** [comment]
@EnnSou 你好，这是由于之前版本里，缺少了对拖拽到网页的文件流做处理操作。已更新版本尝试解决该问题，请试试最新版本看看问题是否解决。

谢谢反馈！
