### ISSUE TITLE
macOS 12.5.1 端口有冲突

### ISSUE THREAD

**Issue by gongshuicheng** [ZhangGe6/onnx-modifier#15]
设备：Macbook Air M1
运行报错：
* Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> Sharing.

**Comment by ZhangGe6** [comment]
你好，`onnx-modifier`默认使用`5000`号端口，您所遇到的问题是由于机器的`5000`号端口已被其他程序使用，故导致冲突。

已更新版本，现支持用户传入自定义配置参数（如`port`），您可使用
```bash
python app.py --port=<available_port>
```
其中`available_port`指当前机器中未被占用的端口，看看问题是否解决。

谢谢反馈！
