### ISSUE TITLE
Graph modified but output is not giving

### ISSUE THREAD

**Issue by rajan780** [ZhangGe6/onnx-modifier#16]
Hi @ZhangGe6 
First of all thanks for this wonderful tool. 
Actually i modified my graph using this tool and when i am viewing in netron it is proper but the node which i added is giving no output means i can't see what shape it output or what type it outputs it just showing the output name as text. can you please help me to fix this? 

Thanks in Advance:)

**Comment by ZhangGe6** [comment]
@rajan780 Thanks for your feedback. It is suggested to add a **model** output following the newly added node, as is illustrated [here](https://github.com/ZhangGe6/onnx-modifier#add-new-model-outputs). Then the shape/type information of the newly added node output will show as model output.

For example, we have a demo model: `input->node1->node2`. We add a new node `node3` and get a new model `input->node1->node2->node3`. If we want to see the shape/type information of `node3`, we should click `node3` and click `Add Output` button in the invoked sidebar. Then the shape/type information of `node3` will show as model output in the saved model.

**Comment by ZhangGe6** [comment]
An alternative way is to run the `shape_inference` method manually by 
```python
import onnx
from onnx import shape_inference
path = "..."
onnx.save(onnx.shape_inference.infer_shapes(onnx.load(path)), path)
```
As reported [here](https://github.com/lutzroeder/netron/issues/71#issuecomment-395771020).
