### ISSUE TITLE
How to change batchsize ?

### ISSUE THREAD

**Issue by Arche-Logos** [ZhangGe6/onnx-modifier#17]
![image](https://user-images.githubusercontent.com/39848543/189254057-595a89ce-93c5-4d62-b32e-151cb780a3bd.png)

**Comment by ZhangGe6** [comment]
Thanks for the feedback! The feature of `change batch size` is not supported now and coming soon.

**Comment by ZhangGe6** [comment]
@Arche-Logos The feature of `change batch size` is now supported. Please refer to [readme](https://github.com/ZhangGe6/onnx-modifier#change-batch-size) for more details.
