### ISSUE TITLE
Unable to download model even without modification

### ISSUE THREAD

**Issue by 111qqz** [ZhangGe6/onnx-modifier#18]
![image](https://user-images.githubusercontent.com/30498101/191144726-ee41bcb4-2aab-4af1-9c3a-43a0eeb2b66a.png)

![image](https://user-images.githubusercontent.com/30498101/191144741-bf3d267a-b12e-45e4-b1ac-970c3e8a960a.png)

This problem can be reproduced with any model，like [resnet18](https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet18-v2-7.onnx)

**Comment by ZhangGe6** [comment]
@111qqz Thanks for the feedback! This was really a bug and has been fixed.
