### ISSUE TITLE
How to prohibit auto-translation to chinese!

### ISSUE THREAD

**Issue by SStarver** [ZhangGe6/onnx-modifier#20]
> Hi,there
> I've encountered a problem that  once I open the app on windows, everything would be ugly translated into chinese. How could I prevent this from happening? 

<img width="572" alt="problem" src="https://user-images.githubusercontent.com/108868933/197135936-5154639d-d23d-48c0-a017-442ae06fcc55.png">

> Installation by method 2: "launch from executable file"

Wish for solutions!

**Comment by ZhangGe6** [comment]
It is a little confusing. Since you launch `onnx-modifier` from the executable file, please check whether the translation is done by your browser automatically. If so, turn off the automatic translation of the browser and try again.

**Comment by ZhangGe6** [comment]
I am going to close the issue due to inactivity. Feel free to reopen it if the problem still exists.
