### ISSUE TITLE
how to delete constant nodes in onnx? 

### ISSUE THREAD

**Issue by SStarver** [ZhangGe6/onnx-modifier#21]
As shown in pictures below,  when open an onnx modified by onnx-modifier with netron, constant nodes are found. How could I delete these constant nodes with onnx-modifier?

<img width="758" alt="constant_nodes" src="https://user-images.githubusercontent.com/108868933/197147468-125ea70f-f107-4b15-90bb-303a64d8c05c.png">

Sincerely, wish for reply!!

**Comment by SStarver** [comment]
Surprisingly, reopen the modified onnx, constant nodes can be modified now. 
But still, if constant nodes can be editable in the  original onnx, it'll be much more convenient!

problems solved~

**Comment by ZhangGe6** [comment]
Thanks for the feedback! It seems there is a bug in the current version. Would you like to share the ONNX file (if possible), your editing operations, and expected editing effects? It can help to debug a lot. Thanks!

:bulb: If it is not convenient to provide the original whole model file, a part of it (edited from the complete one using `onnx-modifier`) can also serve as a debug hint.

**Comment by ZhangGe6** [comment]
@SStarver Hi, I have refined the editing pipeline to solve the `legacy constant nodes` problem. Welcome to update to the newer version of `onnx-modifier` and have a try.
