### ISSUE TITLE
无法成功插入slice节点，希望增加修改输入通道数的功能

### ISSUE THREAD

**Issue by wwdok** [ZhangGe6/onnx-modifier#22]
作者你好，我的情况是这样的，我的模型是在灰度图上训练的，所以输入的通道数只有1，现在我要把输入的通道数变成3，这样才能享受TNN的加速，但我又不想重新制作数据集和训练，所以我想到的是：第一步，修改输入的通道数从1变成3，即[1,1,192,192]变成[1,3,192,192]；第二步，在输入后面插入一个slice算子，只选取三个通道中的第一个通道。这样我就不用重新训练模型了。
现在我跳过第一步，先尝试第二步插入slice 算子，但遇到了以下问题：
我已经修改了slice的输入和输出
![image](https://user-images.githubusercontent.com/43233772/197326011-e2fe6b01-131f-41e4-9866-80e70625ebed.png)
也修改了第一个卷积的输入
![image](https://user-images.githubusercontent.com/43233772/197326037-bb214035-acd7-409a-a9ae-1152d329e707.png)
可slice算子还是无法成功地与第一个卷积连接。
我使用的onnx模型是：[model.zip](https://github.com/ZhangGe6/onnx-modifier/files/9843784/model.zip)

**Comment by ZhangGe6** [comment]
谢谢反馈！问题收到，正在修复中。

**Comment by ZhangGe6** [comment]
@wwdok 你好，这个issue中包含两个问题：

**1. 关于slice算子无法成功连接**
这一步是上述操作有误。具体来说，在第二步修改“卷积的输入”时，应该填写`Conv0`，而不是`custom_added_Slice0`。（填的应该是节点的输入输出名，而不是节点名）。
- 填写为`Conv0`后，实测可以成功连接。
- 需要指出的是，在每次输入到最后一个字符前，建议稍稍停顿一下，因为`Netron`源码中有大量的异步操作，输入太快可能导致读取不到。

**2. 关于增加修改输入通道数的功能**
该功能目前已经支持，详见[readme](https://github.com/ZhangGe6/onnx-modifier#edit-model-initializers)。就该问题而言，具体设置如下图，实测得到的模型可以正确推理。
<img width="1120" alt="issue22_slice_example" src="https://user-images.githubusercontent.com/63796752/198252717-d8455fb6-169c-42e6-8148-6a6ff44b5ccb.png">

请重新尝试一下，如果还存在问题，欢迎继续交流~

**Comment by ZhangGe6** [comment]
> 我后来再想想，感觉我说的”增加修改输入通道数的功能“好像和你理解的不太一样，我期望的是改变模型输入的通道数，也就是[1,1,192,192]变成[1,3,192,192]，如下图所示：

我也是按照你描述的这样理解的。starts = [0, 0, 0, 0], ends = [1, 1, 192, 192]的slice节点，实现的是取第一个通道。我这边没有做三通道的实验，而是还在一通道的基础上做slice，是想示例一下。因为从三通道中取第一通道，和从一通道中取第一通道，得到的值应该是一样的。
请问是在把输入的通道数从1变成3后，使用出现问题了吗？如果是我没理解对你的意思，也欢迎继续讨论~

”推理形状“的功能确实比较实用，后续会考虑添加支持。多谢建议~

**Comment by ZhangGe6** [comment]
ok!
