### ISSUE TITLE
Feature request: changing output and input shapes

### ISSUE THREAD

**Issue by the-beee** [ZhangGe6/onnx-modifier#23]
It would be nice to be able to change the output shape and data type from the UI. 
The same goes for the input and intermediate tensors :)

**Comment by hset911** [comment]
> @the-beee Hi, thanks for your suggestion!
> 
> To change the model output shape/type, we can add a "converter" node, such as the [`Reshape`](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Reshape) node for changing output shape and the [`Cast`](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cast) node for changing output type.
> 
> For the model input, changing batch size is supported now (see [here](https://github.com/ZhangGe6/onnx-modifier#change-batch-size) for more details). Changing other dimensions can be future work if necessary.

Can you add to modify the input shape?
