### ISSUE TITLE
Any other examples to add nodes, like add a multi-dimension constant?

### ISSUE THREAD

**Issue by ganyz** [ZhangGe6/onnx-modifier#24]
Any other examples to add nodes, like add a multi-dimension constant?

like input is [1,3,480,640] and the constant [1,3,1,1]  (100,100,100)
and we want to broadcast add them ?

Thank you!

**Comment by ZhangGe6** [comment]
> I want to change the params from [1,2,3] to [100,200,300], but I don't know how to modify it in the above box

The following steps should work:
1. copy the items in the `original initializer value`  box (including all the `[` and `]`);
2. paste them in the `This is an initializer, you can input a new value for it here` box;
3. change the values in the pasted box (1 -> 100, 2 -> 100, 3->100);
4. click `Download`.

Feel free to further discussions if problems still exist.

**Comment by ganyz** [comment]
> 



> > I want to change the params from [1,2,3] to [100,200,300], but I don't know how to modify it in the above box
> 
> @ganyz The following steps should work:
> 
> 1. copy the items in the `original initializer value`  box (including all the `[` and `]`);
> 2. paste them in the `This is an initializer, you can input a new value for it here` box;
> 3. change the values in the pasted box (1 -> 100, 2 -> 100, 3->100);
> 4. click `Download`.
> 
> Feel free to further discussions if problems still exist.

It works!
Thank you very much !
