### ISSUE TITLE
Add a Cast node and modify to attribute but keep roll back to NaN

### ISSUE THREAD

**Issue by jjdd88** [ZhangGe6/onnx-modifier#25]
I create a Cast node. to attribute is undefined initially.
I change to float32, float, Float, Float32, FLOAT, ... etc.
No matter what I put, it show NaN later

I change to 1 and it shows float32 later
I thought I make it.  but when I load new model with netron, it say unknown type "1"

Really don't know how to add Cast properly

**Comment by ZhangGe6** [comment]
Thanks for the feedback! Fixing.

**Comment by ZhangGe6** [comment]
@jjdd88 Hi, I have updated `onnx-modifier` to try fixing this problem. Welcome to update to the latest version and have a try.

**Comment by jjdd88** [comment]
Thanks,  it works.  But a small GUI bug.

After I add a Cast node and add output.  I cannot see the output type from Model property.  I need to save the model and reload it to see it.

![modelproperty](https://user-images.githubusercontent.com/8231376/202479857-c7421853-3b50-4501-af4d-cbf644e83819.png)

**Comment by ZhangGe6** [comment]
> After I add a Cast node and add output. I can not see the output type from Model property. I need to save the model and reload it to see it.

Yes, you are right. Instant automatic shape/type inference is not supported in the current version and has been added to the [to-do list](https://github.com/ZhangGe6/onnx-modifier/blob/master/docs/todo_list.md). Stay tuned!

Thanks for your suggestion.
