### ISSUE TITLE
initializer无法修改

### ISSUE THREAD

**Issue by xiaohui0225** [ZhangGe6/onnx-modifier#26]
![image](https://user-images.githubusercontent.com/57162039/202652704-7e16ab70-3cd2-432d-b0f0-f3cd7ee38d11.png)
![image](https://user-images.githubusercontent.com/57162039/202652876-c92b95bc-1b67-4622-82e2-1506fbbc3af3.png)

我按照您的办法修改initializer，修改之后download，但新的onnx中仍未修改。

**Comment by ZhangGe6** [comment]
@xiaohui0225 Thanks for the feedback. An ONNX model with `Constant` nodes will help debug and fix this issue a lot. But after a bunch of searching, I find it is not easy to get one... 

So Is it possible for you to share the model you are editing (or a part of it) for quicker debugging? Thanks a lot.

**Comment by ZhangGe6** [comment]
@xiaohui0225 谢谢反馈！

看起来这是一个`Reshape`节点吗？如果是的话：

- 我这里测试了下，`Reshape`节点是可以正常修改shape值的。请确认一下操作是否有误？（[test_edit_init.onnx](https://github.com/ZhangGe6/onnx-modifier/files/10041646/test_edit_init.zip) 是一个我可以正常编辑的模型，您可以试一试把模型尾部的`Reshape`节点值，从`[1, 2, 32, 12, 12]`更改为`[1, 2, 32, 24, 6]`，来验证操作是否正确。）
- 另须提醒，根据ONNX文档的[Reshape节点说明](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Reshape)，**reshape前后的元素数目应该是相同的**。所以图中所示的操作可能是非法的。

如果不是的话，烦请提供更多信息，这将非常有助于定位和解决该问题。谢谢~！

**Comment by xiaohui0225** [comment]
我使用了您给的onnx文件，在测试修改节点名称时，输入name可以正常修改，但是输出name却不能修改。
我的环境win10， onnx=1.12.0，  flask=2.2.2
















在 2022-11-18 21:33:38，"Zhang Ge" ***@***.***> 写道：

@xiaohui0225 谢谢反馈！

看起来这是一个Reshape节点吗？如果是的话：

我这里测试了下，Reshape节点是可以正常修改shape值的。请确认一下操作是否有误？（test_edit_init.onnx 是一个我可以正常编辑的模型，您可以试一试把模型尾部的Reshape节点值，从[1, 2, 32, 12, 12]更改为[1, 2, 32, 24, 6]，来验证操作是否正确。）
另须提醒，根据ONNX文档的Reshape节点说明，reshape前后的元素数目应该是相同的。所以图中所示的操作可能是非法的。

如果不是的话，烦请提供更多信息，这将非常有助于定位和解决该问题。谢谢~！

**Comment by ZhangGe6** [comment]
@xiaohui0225 谢谢反馈，这个问题我会再看看。请先确认一下initializer能否正常修改？😂

**Comment by ZhangGe6** [comment]
@xiaohui0225 无法修改模型输出名的问题已修复。

**Comment by ZhangGe6** [comment]
因问题无法复现且长时未得回复，本issue将关闭。@xiaohui0225  如果问题仍然存在，欢迎继续讨论。
