### ISSUE TITLE
修改batchSize实际上不起作用

### ISSUE THREAD

**Issue by XiaotaoChen** [ZhangGe6/onnx-modifier#27]
场景描述：将原来onnx模型`batch_size`改为1（即输入尺寸由`[batch_size, 3, 224, 224]`改为`[1, 3,224,224]`），nerton可视化结果符合预期，但在解析modified onnx模型时通过`onnx::ValueInfoProto`获取输入尺寸,如`tensorInfo.shape().dim(i).dim_value()`，结果和`batch_size`相同，均为[0,3,224,224], 模型为开源mobilenet onnx

**可视化**
**原始模型**
<img width="830" alt="image" src="https://user-images.githubusercontent.com/23189018/203694032-586fe750-081b-4341-a097-9008b6285480.png">

**修改batch_size=1后模型**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/23189018/203694089-bad8e219-98b0-4d3a-9f63-a2252a49ae78.png">

**Comment by ZhangGe6** [comment]
@XiaotaoChen 谢谢指出！这是由于原版本中存在的错误，现已修正。

PS：在修正前，由于编辑操作的错误，输入输出batch_size维度上的`1`，实际上是一个字符串...（完美地骗过了眼睛）。所以得到的模型本质上还是dynamic inference的，这时候的`dim_param = "1"`（`1`是字符串），`dim_value = 0`。这也就解释了上述现象。

**Comment by XiaotaoChen** [comment]
> @XiaotaoChen 谢谢指出！这是由于原版本中存在的错误，现已修正。
> 
> PS：在修正前，由于编辑操作的错误实现，导致得到的模型中，输入输出batch_size维度上的`1`，实际上是一个字符串...（完美地骗过了眼睛）。所以得到的模型本质上还是dynamic inference的，这时候的`dim_param = "1"`（`1`是字符串），`dim_value = 0`。这也就解释了上述现象。

ok感谢，之前还遇到其他复杂一点的问题：比如截断网络后，再新增带算子参数的op节点（比如transpose），设置参数后，download会报错。

**Comment by ZhangGe6** [comment]
> 之前还遇到其他复杂一点的问题：比如截断网络后，再新增带算子参数的op节点（比如transpose），设置参数后，download会报错。

谢谢反馈！我这边简单测试了一下，截断网络，再新增transpose节点，可以正常编辑。所以可否再提供一些更详细的问题描述？可以新开一个issue.

**Comment by XiaotaoChen** [comment]
> > 之前还遇到其他复杂一点的问题：比如截断网络后，再新增带算子参数的op节点（比如transpose），设置参数后，download会报错。
> 
> 谢谢反馈！我这边简单测试了一下，截断网络，再新增transpose节点，可以正常编辑。所以可否再提供一些更详细的问题描述？可以新开一个issue.

okok我明天详细整理一下哈

**Comment by XiaotaoChen** [comment]
我重新试了下，能正常编辑导出来，感谢感谢，这个工具很赞
