### ISSUE TITLE
添加sub节点，导出报错

### ISSUE THREAD

**Issue by Li-Lai** [ZhangGe6/onnx-modifier#28]
模型的均值是[0.5,0.5,0.5]，我尝试在onnx的input0后面添加sub节点来实现减均值的操作。但一直没有成功。
下图是正确的onnx的参数：
![image](https://user-images.githubusercontent.com/12853603/203884061-68a2f9e8-6dc8-4eaa-997f-d999d6a95a2b.png)

我把上图中的正确参数：参数和type都复制过来，一直提示错误。

![image](https://user-images.githubusercontent.com/12853603/203884223-a3ae9cf6-7afe-4837-b15e-73ffcb221a09.png)

![image](https://user-images.githubusercontent.com/12853603/203884414-87653a62-7ed4-4d5e-b89f-44391ef82a4f.png)

请教一下：该如何处理呢？【版本是今天下载的新版本】

**Comment by ZhangGe6** [comment]
@Li-Lai 谢谢反馈！之前版本的`type`一栏不会考虑`shape`信息，所以请直接输入`float32`（而不`float32[1,3,1,1]`）试试~

**Comment by ZhangGe6** [comment]
我更新了一个版本，现在对`type`的解析更加友好鲁棒，直接输入`float32[1,3,1,1]`也可以解析成功了。

**Comment by Li-Lai** [comment]
> 我更新了一个版本，现在对`type`的解析更加友好鲁棒，直接输入`float32[1,3,1,1]`也可以解析成功了。

好的，谢谢诶。我去试试。

**Comment by Li-Lai** [comment]
尝试了一下，貌似还是不对。请您再帮忙查看一下：
![image](https://user-images.githubusercontent.com/12853603/203928879-6d750426-c520-460a-a359-05192788d20b.png)

下面两种数据格式，我都尝试了，同样的问题。
![image](https://user-images.githubusercontent.com/12853603/203929209-45d23a99-a3ac-4d5f-95cb-cc71171dfbe7.png)

**Comment by ZhangGe6** [comment]
我这边测试了是正常的诶。
<img width="818" alt="issue28" src="https://user-images.githubusercontent.com/63796752/203938467-3342feda-3b23-4a15-8fd8-24014c706feb.png">

请问是否方便分享一下这个正在编辑的模型（或者它的前面一小截），方便定位问题？

**Comment by Li-Lai** [comment]
好的。我这边上传一下。感谢您的分析和排查。
[model1.zip](https://github.com/ZhangGe6/onnx-modifier/files/10090111/model1.zip)

**Comment by ZhangGe6** [comment]
我这边用您上传的model1.onnx，也是可以正常编辑的诶（得到的模型也可正常inference），有些疑惑。

我的操作是这样的：
1. 点击`Add Node`添加`Sub`节点；
2. 点击`Sub`节点，修改其`INPUTS`的`A`为input0；
3. 点击第一个`Conv`节点，修改其`INPUTS`中的`X`为custom_output_2（此时`Sub`节点连接到了图上）；
4. 点击`Sub`节点，分别在`INPUTS`的`B`的`value`和`type`填入`[[[[0.5]],[[0.5]],[[0.5]]]]`和`float32[1,3,1,1]`；
5. 点击`Download`完成。

<img width="856" alt="issue28_1" src="https://user-images.githubusercontent.com/63796752/203968568-6bb768ce-6300-4a3d-af3b-5b0c865395ce.png">

可否烦请您按照这个步骤试一下是否可以正常编辑。如果可以的话，咱们再对照之前您的操作，定位一下问题在哪里。麻烦啦~！

**Comment by Li-Lai** [comment]
我的操作步骤跟您是完全一致的。我刚才又重新下载了code。
我的系统是：Ubuntu 18.04.5 LTS
下面是我刚才操作的录屏，您帮忙看看步骤是否有问题？
https://user-images.githubusercontent.com/12853603/203979891-7be8c40e-14aa-4e9a-995c-81c09f1761df.mp4

**Comment by Li-Lai** [comment]
我在代码位置加上了您提到的打印语句。输出与您提到的是一致。

![image](https://user-images.githubusercontent.com/12853603/203981935-dc1eb0aa-2b41-4daf-a764-fe992ed8aee4.png)

复现视频：
https://user-images.githubusercontent.com/12853603/203981547-9f0eccae-4ae4-40eb-ac67-8ad96d8fb796.mp4

我的环境：
Ubuntu 18.04.5 LTS
python                                     3.8.3
onnx                                         1.10.0
onnx-simplifier                    0.3.6
onnxoptimizer                      0.2.6
onnxruntime                        1.8.1

**Comment by ZhangGe6** [comment]
@Li-Lai 好的收到，在上面提到的环境配置下，我这边问题也复现了:satisfied:，我来看一看。

**Comment by Li-Lai** [comment]
> @Li-Lai 好的收到，在上面提到的环境配置下，我这边问题也复现了laughing，我来看一看。

好的，辛苦您帮忙排查啦

**Comment by ZhangGe6** [comment]
@Li-Lai 问题定位和解决了:joy:。

**省流版本**：把`onnx`库从`1.10.0`升级到更新的版本（如`1.11.0`），应该就可以了。（我这边一开始用的是`1.11.0`版本，所以能正常编辑）

**具体原因：**
`make_tensor()`[在`1.10.0`版本中的实现](https://github.com/onnx/onnx/blob/rel-1.10.0/onnx/helper.py#L220)为：

```python
def make_tensor(name, data_type, dims, vals, raw=False): 
    ...
    # Check number of vals specified equals tensor size
    size = 1 if (not raw) else (mapping.TENSOR_TYPE_TO_NP_TYPE[data_type].itemsize)
    for d in dims:
        size = size * d
    if (len(vals) != size):
        raise ValueError("Number of values does not match tensor's size.")
    ...
```

[在`1.11.0`版本的实现](https://github.com/onnx/onnx/blob/rel-1.11.0/onnx/helper.py#L251)为

```python
def make_tensor(name, data_type, dims, vals, raw=False): 
    ...
    # Check number of vals specified equals tensor size
    expected_size = 1 if (not raw) else (mapping.TENSOR_TYPE_TO_NP_TYPE[data_type].itemsize)
    # Flatten a numpy array if its rank > 1
    if type(vals) is np.ndarray and len(vals.shape) > 1:
        # NOTE flatten() here
        vals = vals.flatten()
    for d in dims:
        expected_size = expected_size * d

    if len(vals) != expected_size:
        raise ValueError("Number of values does not match tensor's size. Expected {}, but it is {}. "
            .format(expected_size, len(vals)))
    ...
```

关键在于新版本对入参`vals`做了`flatten()`。

在本issue中，`Sub`节点的`initializer`的值（`vals`）为`[[[[0.5]], [[0.5]], [[0.5]]]]`，尺寸（`dims`）为`(1, 3, 1, 1)`。

- `size`，或新版本中的`expected_size`，通过`dims`的累乘后为`3`。

- 而对类型为`numpy.array`的`vals`来说，`flatten()`前后的`len()`值是不同的 [参见](https://stackoverflow.com/a/43082119/10096987)

  ```python
  import numpy as np
  
  vals = np.array([[[[0.5]], [[0.5]], [[0.5]]]])
  print(len(vals))   # 1
  
  vals = vals.flatten()
  print(len(vals))   # 3
  ```

**这也就导致了在`1.10.0`版本中，出现了`len(vals) != size`的情况，报了上面的Error.**

`onnx`官方库也有[issue](https://github.com/onnx/onnx/issues/3115)提到了这个问题。

不知道这算不算`onnx`库里曾经设计的不太合理的地方:upside_down_face:，不过为了兼容更多的`onnx`库版本，我更新了下代码，主动把`vals`做`flatten()`了。

**Comment by Li-Lai** [comment]
原来是这个原因。十分感谢。我明天更新试试，再来反馈。非常感谢今天您的多次协助和解答。

**Comment by Li-Lai** [comment]
已经验证，完美解决，谢谢！
