### ISSUE TITLE
Cannot add reshaper

### ISSUE THREAD

**Issue by jjdd88** [ZhangGe6/onnx-modifier#29]
When try to add reshaper,  don't know how to add static shape for shape input
Feel not correct
![reshaper](https://user-images.githubusercontent.com/8231376/206045284-86fadce8-b35a-4182-a015-b31f276ec7ea.png)

**Comment by ZhangGe6** [comment]
@jjdd88 What you input for the reshape node should work.

What result do you expect and what problems do you encounter? It can be helpful if you can provide more details. Thanks!

**Comment by jjdd88** [comment]
I want to add a reshape at the end, and create an output for it.
when I click download, it failed to download.  but after 2-3 times of try,  I can download.
But after I download,  I check the save model.  It does has reshape at the end but no model output.  
I add output and download again,  still no output.
Must the reshape I add is bad

**Comment by jjdd88** [comment]
I finally make it work.  I end up add reshape + Cast.
Not sure whether I can change type in reshape and save Cast.  The type in reshape is int64 and Cast convert to float
you can close this if you want,  
The system is not stable.  Like if I do something wrong,  correct it not work.  I better to restart app.py.
It finally work just need to try several times.

Thanks
