### ISSUE TITLE
ConstantofShape去除此单个节点

### ISSUE THREAD

**Issue by alimagic** [ZhangGe6/onnx-modifier#3]
![Uploading image.png…]()
不能直接删除ConstantofShape单个节点，想请教如果要删除这个节点这种需要如何操作呐

**Comment by ZhangGe6** [comment]
@alimagic 你好，上面的这张图片不能正常显示，可否重新上传一下？

**Comment by alimagic** [comment]
![image](https://user-images.githubusercontent.com/9319195/173190073-6be5c17b-1593-43df-bb34-0aafe9dbbe41.png)

**Comment by alimagic** [comment]
> @alimagic 你好，上面的这张图片不能正常显示，可否重新上传一下？

好的，感谢回复，可能这个节点需要其他转化么

**Comment by ZhangGe6** [comment]
请问是否方便提供onnx模型以供测试验证？以及您预期的更改效果是怎么样的？

PS：如果第一遍删除后，发现下载得到的模型中，ConstantofShape节点仍存在，可尝试将第一遍修改得到的模型再次导入，删除ConstantofShape节点，看看这次可不可以删去。这可能是之前onnx-modifier版本本身不完善的地方，最近几天会更新新版本，尝试解决这类问题。
