### ISSUE TITLE
Add Reshape but no shape initializer?

### ISSUE THREAD

**Issue by xadxxadx** [ZhangGe6/onnx-modifier#31]
I Add a Reshape, but can not set a initializer for shape?
otherwise, if edit orgin reshape shape, after edited the output shape not change?

**Comment by vgg4resnet** [comment]
same question here   
File "/home/nv/.conda/envs/tf115/lib/python3.7/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
 I remove the part that after reshape
![image](https://user-images.githubusercontent.com/44825736/211128493-8cf6b0bc-ef3a-45bd-89c6-8ce58cd1f25b.png)
![image](https://user-images.githubusercontent.com/44825736/211128533-51ba53da-313d-48cd-b64a-bda45a3aff16.png)

**Comment by ZhangGe6** [comment]
@xadxxadx 
> I Add a Reshape, but can not set a initializer for shape?

Adding the initializer for `shape`  should work. 
You can click the added Reshape node, input the initializer value & type(int64) in the placeholder of `shape`, just like this

<img width="1120" alt="add_new_reshape" src="https://user-images.githubusercontent.com/63796752/213183796-80de222b-9c0d-4bbc-9a6f-57582754f6f9.png">

> otherwise, if edit orgin reshape shape, after edited the output shape not change?

I can not reproduce it. Please provide more information, thanks.

**Comment by ZhangGe6** [comment]
@vgg4resnet After your editing, the output of `Reshape` node becomes the output of the model graph, which must have the type and shape information (as [here](https://github.com/onnx/onnx/issues/2932#issuecomment-666888157) states). However, this `Reshape` node has no type and shape information, causing the issue you are encountering.

It seems the `shape_inferece()` may not work well in your model.
