### ISSUE TITLE
Sometimes when you save it it doesn't save the outputs

### ISSUE THREAD

**Issue by pauldog** [ZhangGe6/onnx-modifier#32]
I am using the Windows 64-bit version. 
Steps: open mnist-1.onnx file. Click download. Then open modified-mnist-1.onnx This is what I see:
[screenshot](https://drive.google.com/file/d/1INv51e-HG4tR-S4xeghCfSyinFMNFXKD/view?usp=share_link)

**Comment by ZhangGe6** [comment]
@pauldog Thanks for reporting! This issue is reproduced and I am trying to fix it.
