### ISSUE TITLE
生成的模型无效

### ISSUE THREAD

**Issue by MrLuer** [ZhangGe6/onnx-modifier#37]
可以加节点, 但是生成的模型是无效的, 填入的节点的值似乎没有起到作用. 导出的模型用netron看新增的节点是没有值的(正常的节点能看到值), 用onnxruntime使用导出的模型推理会报错

**Comment by MrLuer** [comment]
![飞书20230216-114213](https://user-images.githubusercontent.com/33979932/219263448-cefb8f67-e7ab-4542-8139-d0026ce579d9.jpg)
![飞书20230216-114323](https://user-images.githubusercontent.com/33979932/219263457-4a3c3256-44fe-4d04-8aa3-c8b6f10f42a0.jpg)

**Comment by MrLuer** [comment]
![飞书20230216-114719](https://user-images.githubusercontent.com/33979932/219263693-ae4ccf7c-5b81-4ea2-8add-0b4b66ec5c1d.jpg)

**Comment by ZhangGe6** [comment]
@MrLuer 谢谢反馈。

请在为均值填写的`type`一栏中，填写`float32[1,3,1,1]`（而非`float32(1,3,1,1)`），看看问题是否解决。

**Comment by MrLuer** [comment]
> @MrLuer 谢谢反馈。
> 
> 请在为均值填写的`type`一栏中，填写`float32[1,3,1,1]`（而非`float32(1,3,1,1)`），看看问题是否解决。

谢谢, 问题解决
