### ISSUE TITLE
[Bug Report] Does onnx-modifier support modification on scalar initializer?

### ISSUE THREAD

**Issue by HYLcool** [ZhangGe6/onnx-modifier#38]
I got an onnx with QuantizeLienar and DequantizeLinear nodes in it, and the scale of these nodes are scalar.

When I try to modify the scale initializer to a scalar value like below, the scale initializer becomes 0 in the downloaded modified onnx model.
- modification process:
![image](https://user-images.githubusercontent.com/12782861/219553491-bbe7ba23-69b1-4dfd-8a02-5e985619b73b.png)
- modified onnx model:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/12782861/219553626-d06b5c27-0a61-409b-9279-8704e61890da.png">

So I wonder if onnx-modifier support modification on scalar initializer. Thanks!

**Comment by HYLcool** [comment]
BTW, I tested the function `parse_str2np` [here](https://github.com/ZhangGe6/onnx-modifier/blob/9c69a8ee6d4a694a950bc71b5595789dd5b3adb7/utils/parse_tools.py#L7). The results below shows that the current version of onnx-modifier might not support scalar initializer modification.
```python
print(parse_str2np('0.23', 'float32')
# array(0., dtype=float32)

print(parse_str2np('[0.23]', 'float32')
# array([0.23], dtype=float32)
```

**Comment by ZhangGe6** [comment]
@HYLcool This was really a bug and has been fixed. Thanks for reporting!
