### ISSUE TITLE
精度问题

### ISSUE THREAD

**Issue by MrLuer** [ZhangGe6/onnx-modifier#39]
增加的节点上填入的值与导出的值不一致, 是类型转换导致的精度截断?

**Comment by MrLuer** [comment]
[[[[0.0171247538316637]],[[0.0175070028011204]],[[0.0174291938997821]]]]

**Comment by ZhangGe6** [comment]
@MrLuer 谢谢反馈，问题已定位，是类型转换导致的精度截断。

```python
import numpy as np

val = 0.0171247538316637
np_fp32 = np.array(val, dtype=np.float32)
np_fp64_convert = np.array(np_fp32, dtype=np.float64)

print(val)                        # 0.0171247538316637 (原始数值，Python内置浮点格式，float64)
np.set_printoptions(precision=20)
print(np_fp32)                    # 0.017124753 (保存模型时，转换为float32 -> 精度损失)
print(np_fp64_convert)            # 0.017124753445386887 (对新模型可视化时，转换为float64)

np_fp64 = np.array(val, dtype=np.float64)
print(np_fp64)                    # 0.0171247538316637 
```

可视化时，一律是转化为按照float64格式来显示的（即使是float32格式）。而在保存时，会根据输入的数据类型（type=float32）转换为float32格式，发生精度损失。

正在尝试该问题的解决方案。顺便问一下，该精度损失对模型的最终输出影响大吗？

**Comment by MrLuer** [comment]
测试了2000张图片推理, 直接用onnx推理准确率没有损失,但是用该onnx量化后的模型有近一个点的准确率下降(正常是不会下降).

**Comment by ZhangGe6** [comment]
不确定有没有理解对你的意思。

> 直接用onnx推理准确率没有损失

是指在发生 本issue中提到的类型转换精度损失 前后，模型输出准确率相同？

> 量化后的模型有近一个点的准确率下降(正常是不会下降)

请确认模型准确率下降是由于 本issue中提到的类型转换精度损失 还是 量化 导致的。

**Comment by MrLuer** [comment]
是issues中提到的类型精度损失导致的下降,  通过量化模型显现出来
