### ISSUE TITLE
无法在输出节点前增加新节点

### ISSUE THREAD

**Issue by wwdok** [ZhangGe6/onnx-modifier#40]
作者你好，我想在输出节点前增加一个argmax节点，该节点位于Add和heatmap之间，最后还要把模型输出名从heatmap重命名成indexmap，如下图所示：
![image](https://user-images.githubusercontent.com/43233772/220532073-a32b465c-3d7b-40b4-8daf-5d3b5d99494f.png)
但是我在操作过程中遇到问题，就是Add节点的输出张量名我无法将其从indexmap修改成heatmap（改成其他名字也不可以），好像Add的输出张量名跟模型的输出节点名绑定死了，输出节点名是什么，Add的输出张量名就是什么，见下面视频的后面部分
https://user-images.githubusercontent.com/43233772/220515357-088b3043-770a-4009-86f3-ff40b977f8e7.mp4
模型：
[model.zip](https://github.com/ZhangGe6/onnx-modifier/files/10800425/model.zip)

**Comment by ZhangGe6** [comment]
谢谢反馈，问题收到并复现，会在这两天尽快处理。

**Comment by ZhangGe6** [comment]
@wwdok 哈喽，问题修复（出了点小状况，今天才修好...），欢迎使用。

在输出节点前增加一个argmax节点，具体操作为：
1. 点击`heatmap`输出节点，在弹出的侧边栏下方，点击`delete the output`;
2. 添加`Argmax`节点，修改其input为`heatmap`，output为`indexmap`，并编辑其各属性值;
3. 在`Argmax`节点的侧边栏下方点击`Add output`.
4. 点击download即可。
