### ISSUE TITLE
[Bug Report] aotumatically add a tensor type to model

### ISSUE THREAD

**Issue by HYLcool** [ZhangGe6/onnx-modifier#41]
Hi, I met a bug-like problem here.

Suppose I open a quantized onnx model in onnx-modifier and download it directly. In that case, it will add an explicit tensor type to some ops, such as QuantizeLinear, even with nothing modified.

The figure below shows the explicit type added by onnx-modifier automatically and there is no type information in the original model at the same tensor.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/12782861/220548862-1b2424fb-4ee4-42aa-af1a-67e7a77a5861.png">

- ref onnx: [link](https://drive.google.com/file/d/1P1sDZaF2g9_9Xh0_yxCYemWdTHpcrY9b/view?usp=share_link)
onnx-modifier will add type 'uint8' to the outputs of all QuantizeLinear ops in this onnx model.

We hope that onnx-modifier will keep everything that isn't modified the same as before. Thanks!

**Comment by ZhangGe6** [comment]
Hi, thanks for the feedback.

The type 'uint8' of the outputs of all QuantizeLinear ops is added **unexpectedly** by the automatic `shape inference` when saving the model. 

Automatic `shape inference` is a feature I have struggled with whether to add it or not for a long time. It can be [incomplete](https://github.com/onnx/onnx/blob/main/docs/ShapeInference.md#limitations), unstable, and may cause some unexpected effects (like the one in this issue).

I have updated the code.  `Shape inference` is an optional function now. Just click the `Download` button, leaving the `shape inference` checkbox unselected, then the identical model is supposed to be saved.

<img width="276" alt="issue41" src="https://user-images.githubusercontent.com/63796752/220677793-7d234f49-be52-4342-bd82-ea3811c84717.png">
