### ISSUE TITLE
选中节点后点击add output没有反应

### ISSUE THREAD

**Issue by cloud9wj** [ZhangGe6/onnx-modifier#43]
如题，想在某个节点增加输出但是点击后没有用，没有显示输出节点

**Comment by ZhangGe6** [comment]
@cloud9wj 谢谢反馈，问题无法复现。可否提供更详细的操作信息或提供模型文件？

**Comment by TimeIsMe** [comment]
遇到同样问题，尝试先download再打开保存的modified_yolov7x.onnx文件，之后点击add output成功。
