### ISSUE TITLE
使用 windows executable file修改模型后 download模型失败

### ISSUE THREAD

**Issue by Francis235** [ZhangGe6/onnx-modifier#47]
![img](https://user-images.githubusercontent.com/51819537/227118167-b71772d0-0d3b-4602-b1c7-99132c25a7cd.png)

**Comment by ZhangGe6** [comment]
@Francis235 谢谢反馈！麻烦再提供具体的模型编辑操作，以及终端输出的报错信息，方便定位问题。

**Comment by xuleizhai-ship-it** [comment]
<img width="765" height="519" alt="Image" src="https://github.com/user-attachments/assets/79214c98-9f8e-48e8-93c6-6cf71afa4a66" />  遇到了同样的问题
