### ISSUE TITLE
数据type仍存在问题

### ISSUE THREAD

**Issue by gerry520** [ZhangGe6/onnx-modifier#48]
![7396a901f7209ae931dcceb7f2a3f93](https://user-images.githubusercontent.com/64216665/227405417-48c4f4a3-1e80-40c9-9047-d6e4d4b0114c.png)

删除一个reshape节点后，修改了transpose的属性，但是最后输出的type存在问题。

**Comment by ZhangGe6** [comment]
@gerry520  谢谢反馈！当前版本不支持即时的形状推导（shape inference）。需要在修改节点后，在下载时勾选“shape inference”，得到的模型，对应尺寸信息即会更新。
