### ISSUE TITLE
怎么设置argmax 输出output的类型

### ISSUE THREAD

**Issue by ZJDATY** [ZhangGe6/onnx-modifier#49]
![image](https://user-images.githubusercontent.com/29767049/231417769-a010f760-a015-4b76-b733-275c12c42a2d.png)
argmax是我添加的节点，原本只有一个输出outputs，我想设置argmax的结果output为

float32[1,1,512,512]

但是无论我在这个框里写什么 ，他都没法正确生成output。想请教应该怎么写。

**Comment by ZhangGe6** [comment]
@ZJDATY 无须在框中输入信息（输入框用于键入initializer信息）。

在添加`Argmax`节点后，点击其对应的`Add Output`，为其新增输出即可，如下图所示。

<img width="1112" alt="issue49" src="https://user-images.githubusercontent.com/63796752/231500827-d2412acb-9c31-413b-b9b4-0849723bf1c2.png">

**Comment by ZJDATY** [comment]
> @ZJDATY 无须在框中输入信息（输入框用于键入initializer信息）。
> 
> 在添加`Argmax`节点后，点击其对应的`Add Output`，为其新增输出即可，如下图所示。
> 
> <img alt="issue49" width="1112" src="https://user-images.githubusercontent.com/63796752/231500827-d2412acb-9c31-413b-b9b4-0849723bf1c2.png">

那他添加的output 会自动设置参数类型吗 ，我看别人的模型会有1x512x512.但是我点击output后，引导线旁边没有这个 1x512x512.还有数据类型是自动设置的吗。比如int64 ，int32，float32这些，可以设置吗

**Comment by ZJDATY** [comment]
这是我从别的地方找的代码，可以添加argmax，添加了能运行成功，但是最终的解析output里不对。能帮我看一下吗

```
import onnx
from onnx import numpy_helper
from onnx import TensorProto

# Load the ONNX model
model = onnx.load('D:/Users/Administrator/Desktop/a/deeplab.onnx')

# Get the original output node
output_node = model.graph.output[0]

# Add a new node with the ArgMax operation
argmax_node = onnx.helper.make_node(
    'ArgMax',
    inputs=[output_node.name],
    outputs=['output'],
    axis=1,
    keepdims=1,
    select_last_index=0
)
model.graph.node.append(argmax_node)

# Update the output of the ONNX model to be the output of the Reshape node
model.graph.output.pop()
model.graph.output.append(onnx.helper.make_tensor_value_info(
    'output',
    output_node.type.tensor_type.elem_type,
    [1, 512, 512]
))

print(output_node.type.tensor_type.elem_type)
# Save the modified ONNX model
onnx.save(model, 'modified_model.onnx')

```

**Comment by ZhangGe6** [comment]
> 这是我从别的地方找的代码，可以添加argmax，添加了能运行成功，但是最终的解析output里不对。能帮我看一下吗

@ZJDATY 这个代码需要做两处修改：
```python
argmax_node = onnx.helper.make_node(
    'ArgMax',
    inputs=[output_node.name],
    outputs=['output'],
    axis=1,
    keepdims=0,           # <----
    select_last_index=0
)
```
原因同上。

```python
model.graph.output.append(onnx.helper.make_tensor_value_info(
    'output',
    TensorProto.INT64,  # <----
    [1, 512, 512]
))
```
`Argmax`节点输出为int64类型。`output_node.type.tensor_type.elem_type`对应原始模型的输出类型，可能为float等，直接套用过来导致类型不匹配。

另外建议提问时，问题描述可以尽量明确😂，比如”能运行成功，但是最终的解析output里不对“这样的表述很容易让人get不到意思。

**Comment by ZJDATY** [comment]
@ZhangGe6  哇 我遇到灵异事件了，outputs里面 是[1x2x512x512] . 用它作为ArgMax的输入，输出[1x512x512]的output。

**Comment by ZJDATY** [comment]
非常感谢
