### ISSUE TITLE
Adding output doesn't work

### ISSUE THREAD

**Issue by asyms** [ZhangGe6/onnx-modifier#51]
Hi,

Thank you for creating this tool. It's absolutely great!

## Problem

Adding an output as shown here: https://github.com/ZhangGe6/onnx-modifier#add-new-model-outputs doesn't work.

## Steps to reproduce the issue:
Load in [squeezenet1.0-12.onnx](https://github.com/onnx/models/blob/main/vision/classification/squeezenet/model/squeezenet1.0-12.onnx)
Click on any node
Click on "Add output"
Nothing happens

Kind regards,
Arne

**Comment by ZhangGe6** [comment]
@asyms Thanks for reporting! However, I can not reproduce it on my computer. Following the steps, I get the results as expected:

<img width="1119" alt="issue51" src="https://user-images.githubusercontent.com/63796752/232262220-b003a052-4e07-40b5-9423-05d7c54f7fa1.png">

So can you provide more clues for debugging? Here are some optional ways:
- Turn on the developer mode of the browser (click `f12` if you are using Chrome), and see whether there are error logs produced after clicking `Add output`.
- See whether there are error logs produced in the console after clicking `Download`.

**Comment by asyms** [comment]
I tried again, and now it works. I suppose it was a browser issue on my end.

Thanks for following up.
Arne

**Comment by zhouxiao999** [comment]
I still encountered this issue using the latest version。
Does anyone know why？
