### ISSUE TITLE
Add output failed in last three nodes

### ISSUE THREAD

**Issue by zhouxiao999** [ZhangGe6/onnx-modifier#53]
I try to delete the last nodes until conv node，and then add three new output。After I  download the final onnx file，I found there are no output nodes。I uploaded the original onnx file。

链接：https://pan.baidu.com/s/11z9JzkDRAeUo-DIlchV4Xw 
提取码：j16o

**Comment by ZhangGe6** [comment]
Thanks for reporting! I will try to reproduce and fix it.

**Comment by ZhangGe6** [comment]
@zhouxiao999 Hello, I have uploaded a new version to fix the problem. It seems that it works well for your uploaded model.
<img width="407" alt="issue55" src="https://github.com/ZhangGe6/onnx-modifier/assets/63796752/e79e90f0-9751-496c-b64f-6525459916b1">

The new feature relies on the [onnx-tool](https://pypi.org/project/onnx-tool/) package, so you need install it firstly
```
pip install onnx-tool
```
Then update `onnx-modifier` to the latest version and have a try..
