### ISSUE TITLE
Cannot always add outputs

### ISSUE THREAD

**Issue by mcusgithub** [ZhangGe6/onnx-modifier#57]
Sometimes, output(s) cannot be added / saved.

To reproduce:
- Load squeezeNet (link provided in the help)
- Delete the "softmaxout_1" **output** = Ok
- Select the "softmaxout_1" **node**
- Click "Add Output" = nothing happens = no output is created

This happens with other models (without deleting the output first as above; this is just to show how to reproduce the issue). It seems to happen when the selected node is a 'leaf' = last one on a branch. 

Thank you for your help.

**Comment by mcusgithub** [comment]
- Workaround: Load / Delete node / Save / Re-load onnx / Add Output / Save model again.
- This workaround is also required to get the "Add Node" functionality to work properly in some cases

**Comment by ZhangGe6** [comment]
@mcusgithub Thanks for reporting! The problem has been reproduced and I will try to fix it soon.

**Comment by WangFengtu1996** [comment]
* 在yolov7 onnx 模型中， 删除concat节点以及后面的output，可以download 模型
* 但是添加输出的时候，无法download模型，输出设置batch 数也没有响应

**Comment by ZhangGe6** [comment]
@WangFengtu1996 谢谢反馈，该问题可能和#72原因相同。请使用最新代码，看看问题是否还存在。同时也可查看终端，显示的报错信息，可以帮助定位问题。

**Comment by ZhangGe6** [comment]
@mcusgithub Hello, I have updated the code to fix the adding output issue (after a very long delay :sweat_smile:). You can update the code to the latest version, and see whether it works.

**Comment by ZhangGe6** [comment]
This issue is going to be closed due to inactivity. Free free for more discussions if problems still exist.

**Comment by mcusgithub** [comment]
Does not seem to work still

**Comment by ZhangGe6** [comment]
@mcusgithub Thanks for reporting. Does adding output works correctly for squeezeNet in the first comment now?

**Comment by ZhangGe6** [comment]
@mcusgithub Thanks for reporting. As discussed in #75, with the latest code, the "adding output" function should be more robust than before. I have tested both the squeezenet and YOLOv8n. Adding output for both models works as expected.
