### ISSUE TITLE
Failed to download onnx model

### ISSUE THREAD

**Issue by zgp81613** [ZhangGe6/onnx-modifier#58]
After adding one output to a large onnx model(say, 400M),  then click download button,  and nothing happened.

**Comment by liguang-ops** [comment]
+1

**Comment by ZhangGe6** [comment]
@zgp81613 @liguang-ops Thanks for reporting, and sorry for the late response.

This is a known issue. The editing operations can only take effect after **the whole model** is loaded. So when the model is large, we may need to wait for a while to load it. A tip is to watch the log in the console:
```
loading model...
<This can take a while if the model is large>
load done!
```
`loading model...` means the model is being loaded. After `load done!` shows up, we can start to edit the model.
