### ISSUE TITLE
在shape inference後產生錯誤的output shape

### ISSUE THREAD

**Issue by alan870616** [ZhangGe6/onnx-modifier#59]
![未命名1](https://github.com/ZhangGe6/onnx-modifier/assets/30833410/cc867437-83c1-47eb-b318-35d493ca7ad0)
![未命名2](https://github.com/ZhangGe6/onnx-modifier/assets/30833410/91117513-7b2b-4555-8b45-419e7c3e9513)
如圖所示，將原本的model勾選shape inference後會從原本的output shape從 float32[1, 8400, 80] -> float32[1]

**Comment by ZhangGe6** [comment]
@alan870616 Sorry for the late response, and thanks for reporting.

It seems that shape inference function doesn't work correctly. 

Can you provide the log in the console? It can give helpful clues to fix the problem.

**Comment by alan870616** [comment]
![image](https://github.com/ZhangGe6/onnx-modifier/assets/30833410/1f5c191d-60df-43a2-a2c8-8b6a3c0da7b7)
Thanks for reply.
It seems there were not error reported in the console.
The model what I use is the yolov8n which provided by offical 
The package version of my environment:
python: 3.8.16
onnx: 1.13.0
onnx_tool: 0.6.4

**Comment by ZhangGe6** [comment]
@alan870616 Hello, I have uploaded a new version to fix the problem. Please update to the latest version and have a try.
