### ISSUE TITLE
请问怎么传维度

### ISSUE THREAD

**Issue by qq1628qq** [ZhangGe6/onnx-modifier#6]
我在使用reshape的时候，发现无法定义shape的大小，请问这点是什么处理的呢？谢谢

**Comment by ZhangGe6** [comment]
reshape节点的维度信息，在ONNX模型中是以Tensor的形式保存在图的initializer中的。

增加包含initializer的节点，**在目前版本是暂不支持的**，不过这项功能已经加入了[to do list](https://github.com/ZhangGe6/onnx-modifier/blob/master/docs/todo_list.md)，会争取尽快完善。谢谢反馈！
