### ISSUE TITLE
Nodes in a graph must be topologically sorted

### ISSUE THREAD

**Issue by colchicinewf** [ZhangGe6/onnx-modifier#61]
When i add three node in the graph, and export the model.when i use onnx.checker.check_model(model). 
it appear  that
' Nodes in a graph must be topologically sorted:
'
I think that  it should sort the nodes when export the model while add nodes.

**Comment by ZhangGe6** [comment]
@colchicinewf Thanks for reporting. This is a known problem and I haven' t found a good solution to handle this.

However, we can still get correct inference results with the model containing nodes which are not topologically sorted.
