### ISSUE TITLE
修改后下载得到的模型没有变化

### ISSUE THREAD

**Issue by wangzhaode** [ZhangGe6/onnx-modifier#64]
修改了一些属性和节点，web页面看已经修改了，下载得到的模型仍然是原模型

**Comment by ZhangGe6** [comment]
@wangzhaode 谢谢反馈。请问是否方便提供测试模型，以及具体的操作，帮助排查问题？

**Comment by ZhangGe6** [comment]
由于长时未得到回复，本issue将关闭。如果问题仍然存在，欢迎reopen和继续讨论。
