### ISSUE TITLE
Cannot modify the inputs

### ISSUE THREAD

**Issue by piotrwierzba-tplx** [ZhangGe6/onnx-modifier#65]
While it is perfectly possible to create new nodes, outputs and other things, I have so far not seen any possibility to add inputs. This does not allow to make certain modifications, i.e. it's not possible to set weights of a layer as an input. 
Does it still have to be implemented, or did I miss something in the menu?

**Comment by ZhangGe6** [comment]
@piotrwierzba-tplx Thanks for the feednack Adding input is not supported currently. BTW, what does "set weight of a layer as input" mean?

**Comment by piotrwierzba-tplx** [comment]
Hi there, thanks for clarifying that. I wanted to do a cross-correlation (aka convolution) of two inputs (it can theoretically be done by setting weights of a convolution layer to one image, and setting the other one as an input). It however is not the crux of this issue, so we can leave it at that.

**Comment by ZhangGe6** [comment]
@piotrwierzba-tplx Sorry for the late response. Adding input may not be supported in the near future. Could you please try to use the Python API to do it?
