### ISSUE TITLE
关于算子属性的更改

### ISSUE THREAD

**Issue by Xu-Wade** [ZhangGe6/onnx-modifier#68]
我想请教下您基于netron的改动是什么，细节上是如何实现了算子属性的增减更改这一功能的？

**Comment by ZhangGe6** [comment]
主要是在netron可视化的基础上，增加了编辑的功能。

属性的修改逻辑是，在侧边栏捕获到用户对属性值的修改信息，传到后端（onnx_modifier.py），基于修改后的属性值重新生成一个新节点来替换原节点。
