### ISSUE TITLE
new output after Conv layer

### ISSUE THREAD

**Issue by tomoporo** [ZhangGe6/onnx-modifier#7]
Is it possible to add new "out_put layer", for instance, output after a convolution layer.
Sometimes, we might want to check feature maps from the convolution layer as for image recognition.

I'd like to get such output. I found such way for Pytorch and Keras/Tensorflow.
I'd like to do the same thing using onnx model in onnxRT by cutting(?) and modifing the onnx model. 

I can not find tutorial of it. If there exists such exsamples, please teach me.

**Comment by ZhangGe6** [comment]
If you want to compare the output feature of a Conv layer $L$ with another existing feature $F$, you can run the ONNX model using [onnxruntime](https://onnxruntime.ai/), and compare the output of layer $L$ with $F$ offline.

If I am not getting what you mean correctly, you can explain it in more detail for further discussion.

**Comment by ZhangGe6** [comment]
Sorry for the late response. Adding new input/output nodes is not supported in the current version. However, it is indeed a necessary feature and has been added to the [to-do list](https://github.com/ZhangGe6/onnx-modifier/blob/master/docs/todo_list.md). The feature will come soon and you have to add the new output node by ONNX Python API now.

Thanks for the feedback!

**Comment by ZhangGe6** [comment]
Adding new model outputs is supported now. Please see [Readme](https://github.com/ZhangGe6/onnx-modifier#add-new-model-outputs) for more details.

**Comment by coolmian** [comment]
> Adding new model outputs is supported now. Please see [Readme](https://github.com/ZhangGe6/onnx-modifier#add-new-model-outputs) for more details.

The new model outputs does not support defining shape and data-type, different from the original model output format. Cannot be used as normal model.

in Python，
you can use these code to find the difference between the modified model and the original model：
`
import onnx
model = onnx.load('efficientnet-lite4-11-int8.onnx')
graph = model.graph
output = graph.output
print(output)
`

**Comment by ZhangGe6** [comment]
@coolmian Hi, the shape and data type of the added model outputs **are inferred automatically** and should not be defined manually.

I am afraid I haven't got your point (especially when you say "the original model output format"). So feel free for more discussions if problems still exist.

**Comment by coolmian** [comment]
> @coolmian Hi, the shape and data type of the added model outputs **are inferred automatically** and should not be defined manually.
> 
> I am not sure whether I got your point (especially when you say "the original model output format"). So feel free for more discussions if problems still exist.

```
import onnxruntime as rt
sess = rt.InferenceSession("efficientnet-lite4-11-int8.onnx")
results = sess.run(['efficientnet-lite4/model/head/Squeeze:0_quantized'], {"images:0": img_batch})
```
Thank you for your attention.

But can you provide a sample code for using the model after adding the output node? If I do not define the output format manually, these codes will report an error "onnxruntime. capi. onnxruntime _pybind11_state. InvalidArgument: [ONNXRuntimeError]: 2: INVALID_ARGUMENT: Invalid Output Name: efficientnet-lite4/model/head/Squeeze:0_quantized"
