### ISSUE TITLE
Output节点消失了

### ISSUE THREAD

**Issue by jolly-xw** [ZhangGe6/onnx-modifier#70]
模型的Output无法保存：
即使一个有output节点的模型在onnx-modifier中打开，并不进行任何操作，Download下来的新模型的output节点消失不见了。

**Comment by jolly-xw** [comment]
非常感谢作者开源的onnx-modifier，希望作者可以尽快的修复此问题。

**Comment by ZhangGe6** [comment]
@jolly-xw 谢谢反馈。

请问是否在download时勾选了shape inference？

**Comment by jolly-xw** [comment]
勾选或未勾选貌似都一样，我明天可以再试一下



---- 回复的原邮件 ----
| 发件人 | Zhang ***@***.***> |
| 日期 | 2023年08月01日 19:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ZhangGe6/onnx-modifier] Output节点消失了 (Issue #70) |

@jolly-xw 谢谢反馈。

请问是否在download时勾选了shape inference？

**Comment by jolly-xw** [comment]
> 

我看了一下，在web界面添加的output节点只有一个name，而没有维度信息，且对于onnx的model_proto，在web界面中添加的output节点并没有更新到model_proto中，这导致add_output函数什么也没有做。

**Comment by ZhangGe6** [comment]
output的维度信息是自动推导出来的，生成的model output，会自动加入到model_proto中，参见[这段code](https://github.com/ZhangGe6/onnx-modifier/blob/master/onnx_modifier.py#L195~L205)。

请问是否方便提供原始模型文件，供排查问题？谢谢～！

**Comment by jolly-xw** [comment]
> 
您的邮箱，我发您

**Comment by ZhangGe6** [comment]
@jolly-xw 你好，模型收到。可是我本地无法复现output节点消失的问题。我操作的步骤同样是：在onnx-modifier中打开，不进行任何操作，点击Download。

麻烦确认一下，当时出现问题时，是否有做其他操作？另外想确认一下您本地的相关Python库版本是？我本地的版本为：
```python
onnx                         1.12.0
onnx-tool                    0.6.4
flask                        2.2.2
```

**Comment by jolly-xw** [comment]
当时试的时候比较急，我给您的模型什么操作都不做确实不会输出节点消失，不过无法添加新的输出节点。我的环境我周一发您，在公司的服务器上面。



---- 回复的原邮件 ----
| 发件人 | Zhang ***@***.***> |
| 日期 | 2023年08月05日 15:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ZhangGe6/onnx-modifier] Output节点消失了 (Issue #70) |

@jolly-xw 你好，模型收到。可是我本地无法复现output节点消失的问题。我操作的步骤同样是：在onnx-modifier中打开，不进行任何操作，点击Download。

麻烦确认一下，当时出现问题时，是否有做其他操作？另外想确认一下您本地的相关Python库版本是？我本地的版本为：

onnx1.12.0onnx-tool0.6.4flask2.2.2

**Comment by jolly-xw** [comment]
> @jolly-xw 你好，模型收到。可是我本地无法复现output节点消失的问题。我操作的步骤同样是：在onnx-modifier中打开，不进行任何操作，点击Download。
> 
> 麻烦确认一下，当时出现问题时，是否有做其他操作？另外想确认一下您本地的相关Python库版本是？我本地的版本为：
> 
> ```python
> onnx                         1.12.0
> onnx-tool                    0.6.4
> flask                        2.2.2
> ```

抱歉，我没能复现当时的问题，我试了我这边的模型，不做任何操作的时候不会影响原有的输出节点。可能当时我是删除了output，然后又添加了output。
环境：
python 3.9.7
Falsk 1.1.2
onnx 1.14.0
onnx-tool 0.6.4

**Comment by ZhangGe6** [comment]
好的，也许是给新加的output命名和它初始的名字一样导致的。和#71 问题类似，是一个bug，最近我抽时间修复一下。

**Comment by ZhangGe6** [comment]
@jolly-xw 你好，删除了output，再添加了output无法成功的问题，已提交代码进行修复了。方便时可以更新代码至最新版本，看看问题是否解决。

**Comment by ZhangGe6** [comment]
由于长时没有回复，此issue将关闭。如果问题仍然存在，欢迎继续讨论～
