### ISSUE TITLE
添加输出节点的问题

### ISSUE THREAD

**Issue by zccyman** [ZhangGe6/onnx-modifier#71]
删除输出节点output2, 再添加一个输出节点，名称为output2时，总会添加不成功，改为其他名称，就可以成功，请帮忙修改此bug！

**Comment by ZhangGe6** [comment]
@zccyman 谢谢反馈，已提交代码进行修复。请更新至最新代码试试问题是否解决。

**Comment by ZhangGe6** [comment]
由于长时没有回复，此issue将关闭。如果问题仍然存在，欢迎继续讨论～
