### ISSUE TITLE
关于增加节点clip、div 属性

### ISSUE THREAD

**Issue by Phil-Lin** [ZhangGe6/onnx-modifier#73]
你好：
        我在增加节点clip和div，然后不知道input里面选项如何填写吗？总是输出错误。
![image](https://github.com/ZhangGe6/onnx-modifier/assets/52906245/e25f89fb-048d-4661-9daa-dd10c0d915c6)

**Comment by ZhangGe6** [comment]
@Phil-Lin 谢谢反馈！您在截图中的操作是正确的，报错是因为代码中对标量的initializer支持不完善导致的。

我提交了一份代码修复该问题。请拉取最新代码再尝试一下。

**Comment by ZhangGe6** [comment]
由于长时未得到回复，本issue将关闭。如果问题仍存在，欢迎reopen和继续讨论。
