### ISSUE TITLE
修改const tensor值不生效

### ISSUE THREAD

**Issue by FdyCN** [ZhangGe6/onnx-modifier#76]
首先我按照这样的方式和顺序进行了修改
![image](https://github.com/ZhangGe6/onnx-modifier/assets/80800417/3187613a-1a5e-444d-b50b-5c99a1dae803)

然后得到结果在netron可视化中是这样的，看着reshape shape tensor的修改并没有生效：
![image](https://github.com/ZhangGe6/onnx-modifier/assets/80800417/e801eb39-5da2-4ecd-b5f8-43e5c7facbc7)

请问是哪里操作的不对吗？

**Comment by ZhangGe6** [comment]
@FdyCN 谢谢反馈。reshape的shape tensor修改没有生效，以及shape inference出错都是预期外的。请问是否方便提供原始ONNX模型便于排查问题？

**Comment by ZhangGe6** [comment]
@FdyCN 由于长时未得到回复，且本地无法复现，本issue将被关闭。如果问题仍然存在，欢迎reopen和继续讨论。
