### ISSUE TITLE
添加Add  Div  Clip之后    对生成之后得onnx进行onnxsim,报错

### ISSUE THREAD

**Issue by QIANXUNZDL123** [ZhangGe6/onnx-modifier#78]
![image](https://github.com/ZhangGe6/onnx-modifier/assets/46549527/fd023b0e-cd32-4d78-83a3-fb7b28ebdd75)
我添加这三个算子之后，进行了onnxsim就报错了，，
![image](https://github.com/ZhangGe6/onnx-modifier/assets/46549527/10be54f7-8ac9-4ea0-9eb0-5133a2601b3f)
请问这是什么原因导致得？？

**Comment by ZhangGe6** [comment]
@QIANXUNZDL123 谢谢反馈。这是由于由onnx-modifier新增的节点，不确保是拓扑排序的。该问题正在修复中。

可暂时采取以下workaround：对onnx-modifier得到的模型，先使用[graphsurgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html)进行一遍拓扑排序
```bash
# install graphsurgeon
pip install nvidia-pyindex
pip install onnx-graphsurgeon
```

```python
import onnx
import onnx_graphsurgeon as gs

src_model_path = "modified_xyz.onnx"
dst_model_path = "dst_model.onnx"

graph = gs.import_onnx(onnx.load(src_model_path))
graph.toposort()
onnx.save(gs.export_onnx(graph), dst_model_path)
```
将得到的`dst_model.onnx`用onnxsim处理。

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 谢谢反馈。这是由于由onnx-modifier新增的节点，不确保是拓扑排序的。该问题正在修复中。
> 
> 可暂时采取以下workaround：对onnx-modifier得到的模型，先使用[graphsurgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html)进行一遍拓扑排序
> 
> ```shell
> # install graphsurgeon
> pip install nvidia-pyindex
> pip install onnx-graphsurgeon
> ```
> 
> ```python
> import onnx
> import onnx_graphsurgeon as gs
> 
> src_model_path = "modified_xyz.onnx"
> dst_model_path = "dst_model.onnx"
> 
> graph = gs.import_onnx(onnx.load(src_model_path))
> graph.toposort()
> onnx.save(gs.export_onnx(graph), dst_model_path)
> ```
> 
> 将得到的`dst_model.onnx`用onnxsim处理。

多谢，我试试看

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 谢谢反馈。这是由于由onnx-modifier新增的节点，不确保是拓扑排序的。该问题正在修复中。
> 
> 可暂时采取以下workaround：对onnx-modifier得到的模型，先使用[graphsurgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html)进行一遍拓扑排序
> 
> ```shell
> # install graphsurgeon
> pip install nvidia-pyindex
> pip install onnx-graphsurgeon
> ```
> 
> ```python
> import onnx
> import onnx_graphsurgeon as gs
> 
> src_model_path = "modified_xyz.onnx"
> dst_model_path = "dst_model.onnx"
> 
> graph = gs.import_onnx(onnx.load(src_model_path))
> graph.toposort()
> onnx.save(gs.export_onnx(graph), dst_model_path)
> ```
> 
> 将得到的`dst_model.onnx`用onnxsim处理。

你好 为啥我这不是张量的形式float32[1]  但是设置了float32[]   float32[1]  最后都变成这样了   ，请问这是为啥https://github.com/ZhangGe6/onnx-modifier/issues/78#issuecomment-1706667234

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 谢谢反馈。这是由于由onnx-modifier新增的节点，不确保是拓扑排序的。该问题正在修复中。
> 
> 可暂时采取以下workaround：对onnx-modifier得到的模型，先使用[graphsurgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html)进行一遍拓扑排序
> 
> ```shell
> # install graphsurgeon
> pip install nvidia-pyindex
> pip install onnx-graphsurgeon
> ```
> 
> ```python
> import onnx
> import onnx_graphsurgeon as gs
> 
> src_model_path = "modified_xyz.onnx"
> dst_model_path = "dst_model.onnx"
> 
> graph = gs.import_onnx(onnx.load(src_model_path))
> graph.toposort()
> onnx.save(gs.export_onnx(graph), dst_model_path)
> ```
> 
> 将得到的`dst_model.onnx`用onnxsim处理。

请问，，我这设置了float32[]  也设置过float32[1]  但最后为啥还是这样   
![image](https://github.com/ZhangGe6/onnx-modifier/assets/46549527/26969177-04cd-4c6f-b6a6-36db577e85ca)

**Comment by ZhangGe6** [comment]
1. 请问之前的拓扑排序问题，用前面提到的workaround是否解决？
2. Div的修改，期望是什么样的？

**Comment by QIANXUNZDL123** [comment]
> 1. 请问之前的拓扑排序问题，用前面提到的workaround是否解决？
> 2. Div的修改，期望是什么样的？

拓扑排序之前解决了，，Div期望是张量的形式float32[1]这种形式的
![image](https://github.com/ZhangGe6/onnx-modifier/assets/46549527/03616f22-3c8d-4dd8-be04-2c06a39748ca)

**Comment by ZhangGe6** [comment]
@QIANXUNZDL123 “onnx-modifier新增的节点，不确保是拓扑排序的问题”，已提交代码进行修复。如有需要，可拉取最新代码，看看问题是否解决。

**Comment by ZhangGe6** [comment]
> 拓扑排序之前解决了，Div期望是张量的形式float32[1]这种形式的

@QIANXUNZDL123 需要在数值输入框里，填`[6]`，而不是`6`。
<img width="294" alt="issue78" src="https://github.com/ZhangGe6/onnx-modifier/assets/63796752/f30f381a-8500-4e47-9ca4-3ea625c6972f">

**Comment by QIANXUNZDL123** [comment]
> > 拓扑排序之前解决了，Div期望是张量的形式float32[1]这种形式的
> 
> @QIANXUNZDL123 需要在数值输入框里，填`[6]`，而不是`6`。 <img alt="issue78" width="294" src="https://user-images.githubusercontent.com/63796752/266811086-f30f381a-8500-4e47-9ca4-3ea625c6972f.png">

你好，拉取了新得代码之后，无法保存模型了。一直出现错误。。。 

![11111](https://github.com/ZhangGe6/onnx-modifier/assets/46549527/11d95af9-c2b2-4f31-99ac-3c818a9c2694)
![2222](https://github.com/ZhangGe6/onnx-modifier/assets/46549527/3fa8e8f5-eadd-4f96-a7ed-5fd602908c84)

**Comment by ZhangGe6** [comment]
@QIANXUNZDL123 请问在点击Download按钮前，做了哪些操作？是否方便提供原始模型以供复现问题？谢谢。

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 谢谢反馈。请问在点击Download按钮前，做了哪些操作？是否方便提供原始模型以供复现问题？谢谢。
> 
> 同时我新提交了一份代码，把onnx_checker.check_model()默认关闭了，有时候它太严格。之后可能会把它作为一个用户导出模型时的可选项。

链接：https://pan.baidu.com/s/1JIwHMvjdGrwTsc18H78umg?pwd=9gct 
提取码：9gct 
--来自百度网盘超级会员V1的分享 我只是将hardsigmod替换了add div clip  之后点击保存无法保存，上面是带有hardsigmod的原始模型

**Comment by ZhangGe6** [comment]
@QIANXUNZDL123 你好，前阵子太忙才来得及看。看到网盘链接已经失效了。可否重新上传一下？谢谢。

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 你好，前阵子太忙才来得及看。看到网盘链接已经失效了。可否重新上传一下？谢谢。

链接：https://pan.baidu.com/s/1Du8iyCBsPE7QJqxtCAVKFw?pwd=ujv7 
提取码：ujv7 
--来自百度网盘超级会员V1的分享

**Comment by ZhangGe6** [comment]
使用最新代码，本地测试可正常将hardsigmod替换了add div clip并正常保存。
![78](https://github.com/ZhangGe6/onnx-modifier/assets/63796752/c0bfd138-ecc9-4696-a2c0-b56d327d5d7e)
