### ISSUE TITLE
按docker方式 http://127.0.0.1:5000/无法访问，请问是什么原因呢

### ISSUE THREAD

**Issue by hayyaw** [ZhangGe6/onnx-modifier#79]

**Comment by ZhangGe6** [comment]
谢谢反馈。基于docker的启动方式，只在“本机运行docker，本机访问5000号端口”的场景下测试运行过，更复杂的网络场景，可能需要额外的配置。如果没有特别的需求，建议采用基于源码启动的方式（即readme中的方法1）。
