### ISSUE TITLE
能实现将三个输出，修改为一个输出的功能吗？以yolov5为例

### ISSUE THREAD

**Issue by woshishijeishangshangzuidadwk** [ZhangGe6/onnx-modifier#81]
![1695541148522](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/3b16f836-3f8a-4eb7-b2bf-758317569466)
![1695541157336](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/941c8fcc-09e7-41d6-b3c7-9d6fc47c6560)
![1695541136761](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/5d3f2f78-09b9-437d-b636-3a72efd77d42)

**Comment by ZhangGe6** [comment]
麻烦结合图片对需求给出进一步的说明。是希望只保留三个分支中的一个分支，和它的输出吗？这样可以通过把其他两个分支删除掉实现。

**Comment by woshishijeishangshangzuidadwk** [comment]
感谢回复！不是简单的删除分支，类似下面的图，它是一个输出，上面有三个Transpose，Transpose之后本来是三个输出的分支，经过下面的切片，坐标转换等操作，最后concat成了一个输出，我现在有一个三输出的模型，如何去用您的工具实现三输出到这样的单输出ONNX的转换
![1695541157336](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/f74a6e15-1aee-42f2-af60-7cf776fe2a3d)

**Comment by ZhangGe6** [comment]
我理解可以增加Concat节点，把三个分支concat成一个分支。类似地，也可以为每一个分支增加对应的节点，比如Slice等等。不知道是不是正确理解了需求？

**Comment by woshishijeishangshangzuidadwk** [comment]
是的，是这个样子的。是手动添加所有的节点吗？假如要添加Slice，应该怎么填写内容？谢谢

![1695544203556](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/fca84faf-db56-4a67-a3cf-f1e825ec1b67)
![1695544148031](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/6c0dae37-d7fe-41c6-b1f4-aa2893572ddb)

**Comment by woshishijeishangshangzuidadwk** [comment]
[yolov5s_san.zip](https://github.com/ZhangGe6/onnx-modifier/files/12708106/yolov5s_san.zip)
这是三输出的onnx

**Comment by woshishijeishangshangzuidadwk** [comment]
[yolov5s.zip](https://github.com/ZhangGe6/onnx-modifier/files/12708107/yolov5s.zip)
这是单输出的ONNX，我想将三输出的ONNX转换成单输出的ONNX这样

**Comment by ZhangGe6** [comment]
参数的填写可以参照 点击Node Properties->type一栏后的?号弹出的信息，或参考ONNX operator的官方文档。
![Screenshot_20230924_163617.jpg](https://github.com/ZhangGe6/onnx-modifier/assets/63796752/d54ea82d-4b0e-4c05-84a9-0b8eb737c9a1)

添加节点需要逐个添加。

**Comment by woshishijeishangshangzuidadwk** [comment]
好的 多谢！ 
我试一试

**Comment by woshishijeishangshangzuidadwk** [comment]
作者你好，我已经通过add output 添加了输出 ，为什么导出的onnx没有输出呢
![1695546421902](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/e8cd9a1d-af49-4752-ad48-3eec31f2eb51)
![1695546404813](https://github.com/ZhangGe6/onnx-modifier/assets/128468521/db624b55-3054-48a2-920c-d9619a6288de)

**Comment by ZhangGe6** [comment]
这听起来像是个老问题…。可否提供一个可复现的模型（最好是这种状态：基于这个模型，对某一个节点点击add output，即可复现问题）？谢谢！

**Comment by woshishijeishangshangzuidadwk** [comment]
[yolov5s.zip](https://github.com/ZhangGe6/onnx-modifier/files/12708633/yolov5s.zip)
这是模型单输出的onnx，将sigmoid下面的分支全部去掉然后add output三个，但是没有效果

**Comment by qingzhangq** [comment]
> ![1695541148522](https://user-images.githubusercontent.com/128468521/270151298-3b16f836-3f8a-4eb7-b2bf-758317569466.png) ![1695541157336](https://user-images.githubusercontent.com/128468521/270151300-941c8fcc-09e7-41d6-b3c7-9d6fc47c6560.png) ![1695541136761](https://user-images.githubusercontent.com/128468521/270151304-5d3f2f78-09b9-437d-b636-3a72efd77d42.png)

我的onnx模型是单输出应该如何做成三输出

**Comment by ZhangGe6** [comment]
@qingzhangq 删除最后一个Concat节点，然后在末尾三个Reshape节点分别点击Add output.

**Comment by YellowThree-HS** [comment]
> 标转换等操作，最后concat成了一个输出，我现在有一个三输出的模型，如何去用您的工具实现三输出到这样的单输出ONNX的转换

你好，请问你用什么软件添加节点的
