### ISSUE TITLE
delete error

### ISSUE THREAD

**Issue by Lewis-Lu** [ZhangGe6/onnx-modifier#82]
Hi there, 

It seems that the error happens in the save phase after I deleted the node. The parent modules are missed from the node I deleted.

![image](https://github.com/ZhangGe6/onnx-modifier/assets/24478504/b6fe5ff6-6f69-4c34-9d50-ee47b5cef0b8)

I tried to delete cast node 

Then the saved onnx would be 
![image](https://github.com/ZhangGe6/onnx-modifier/assets/24478504/56a66e45-fac8-40bb-bc96-165b507ad8c8)

The procedures were:

select cast, delete single node, enter,
select first conv module, change the input `X` to the img_feat, enter.

Is there any methods for this issue? or I could do a PR for this.
Best,
Lewis

**Comment by ZhangGe6** [comment]
@Lewis-Lu Thanks for reporting. This is a bug and has been fixed. Please update to the latest code and take a try. Feel free for more discussions if any problem still exists.

**Comment by Lewis-Lu** [comment]
Hi @ZhangGe6 ,

Thanks for replying.
The input node preserved successfully, while the output node is lost. We may need adding output check in modify.py

Thanks, 
Lewis

**Comment by ZhangGe6** [comment]
The lost of output node is usually caused by unperfect shape inference. Did you choose "shape inference" when clicking download or change the batch size? Can you provide the ONNX model file (if possible) to help debugging? Thanks.

**Comment by Lewis-Lu** [comment]
Hi @ZhangGe6,

Without shape inference, the output is right.

Thanks,
Lewis
