### ISSUE TITLE
Axis Is Dropped from Attributes After Change

### ISSUE THREAD

**Issue by Dryn** [ZhangGe6/onnx-modifier#83]
Hi @ZhangGe6, I recently modified a model that included a deconvolution (ConvTranspose) with axis=0 and I changed it to axis=1.

Unforuntately, after saving and later reloading it into Netron.app the new axis=1 was not shown anymore.

I really like the tool onnx-modifier, really helpful for quick modifications!

Best regards,
Dryn

**Comment by ZhangGe6** [comment]
@Dryn Thanks for your attention on onnx-modifier. What do you mean by "change the axis of deconvolution from 0 to 1"? 

If possible, can you provide the ONNX model file, your editing operations and expected behaviour to help debugging? Thanks.

**Comment by ZhangGe6** [comment]
I am going to close the issue due to inactivity. Feel free to reopen it if the problem still exists.
