### ISSUE TITLE
ValueError: Unsupported format: '<class 'onnx.onnx_ml_pb2.ModelProto'>'. Supported formats are: dict_keys(['protobuf', 'textproto', 'json', 'onnxtxt'])

### ISSUE THREAD

**Issue by Egorundel** [ZhangGe6/onnx-modifier#85]
@ZhangGe6 Hello, I have a problem with onnx-modifier. When I want to download edited on model, I have a problem with saving:

`ValueError: Unsupported format: '<class 'onnx.onnx_ml_pb2.ModelProto'>'. Supported formats are: dict_keys(['protobuf', 'textproto', 'json', 'onnxtxt'])`

and 

`NameError: name 'onnx_modifier' is not defined`

![Screenshot from 2023-10-28 14-03-52](https://github.com/ZhangGe6/onnx-modifier/assets/65890558/196798f5-8132-4511-b530-c4fb1c3c8dda)

![Screenshot from 2023-10-28 14-04-03](https://github.com/ZhangGe6/onnx-modifier/assets/65890558/f856e603-5408-4270-a05d-47bbca5ce045)

Can you help me, please?

**Comment by ZhangGe6** [comment]
@Egorundel Thanks for reporting with the detailed error log. It seems like an ONNX format problem. Can you open this model successfully using [Netron](https://netron.app/)? If the model can not be opened using Netron either, it is suggested to check your model format or open an issue on the [ONNX github repo](https://github.com/onnx/onnx/issues).

**Comment by Egorundel** [comment]
@ZhangGe6 yes, here is my model in Netron:
![Screenshot from 2023-10-28 17-16-42](https://github.com/ZhangGe6/onnx-modifier/assets/65890558/8a28b097-aa51-41b2-b3ed-1b3b530785e9)

**Comment by Egorundel** [comment]
@ZhangGe6 I can upload my model to some service so you can watch it

**Comment by Egorundel** [comment]
@ZhangGe6 my model on GoogleDrive: [best_ckpt.onnx](https://drive.google.com/file/d/1eV91mRjmOvY0t7qWhTpVh3Uo3YAQkjkA/view?usp=drive_link)

**Comment by Egorundel** [comment]
The problem was solved quite simply: just downgrade the onnx version. I installed `pip install onnx==1.12.0` and everything worked for me without errors.
