### ISSUE TITLE
添加Reshape算子失败

### ISSUE THREAD

**Issue by zerofix2** [ZhangGe6/onnx-modifier#88]
您好，很感谢您开发的工具。我在使用的时候遇到了一个问题，在模型的输出前添加Reshape算子后，使用onnxruntime推理报错，这是报错信息，似乎和Reshape的shape参数有关：
![Q1](https://github.com/ZhangGe6/onnx-modifier/assets/82206397/361f2b3e-9f73-4afe-9b7c-e3f43d5a8664)
这是我在onnx-modifier中设置的参数：
![image](https://github.com/ZhangGe6/onnx-modifier/assets/82206397/33663051-c972-4057-9688-86bc6ea0ef6f)
这是在netron中查看的Reshape算子，看起来也是正常的，请问我应该怎么样设置参数才能得到正确的输出呢
![image](https://github.com/ZhangGe6/onnx-modifier/assets/82206397/95e2609a-8226-4992-b671-7e06a3c3ba33)

**Comment by ZhangGe6** [comment]
Reshape op的shape参数数据类型为int64，请将下图里的float32修改为int64试一试。
![image](https://github.com/ZhangGe6/onnx-modifier/assets/63796752/1ce21a8b-d758-4d48-a25c-3b87a33327af)

**Comment by zerofix2** [comment]
好的，已经修改成功了，感谢您的回复
________________________________
发件人: ***@***.*** ***@***.***> 代表 Zhang Ge ***@***.***>
发送时间: 2023年11月16日 21:15
收件人: ZhangGe6/onnx-modifier ***@***.***>
抄送: zerofix2 ***@***.***>; Author ***@***.***>
主题: Re: [ZhangGe6/onnx-modifier] 添加Reshape算子失败 (Issue #88)


Reshape op的shape参数数据类型为int64，请将下图里的float32修改为int64试一试。
[image]<https://user-images.githubusercontent.com/63796752/283460811-1ce21a8b-d758-4d48-a25c-3b87a33327af.png>

―
