### ISSUE TITLE
不能修改initializer的值

### ISSUE THREAD

**Issue by Ryuk17** [ZhangGe6/onnx-modifier#89]
我想修改算子输入的initializer value，但是修改后保存没有起作用，请问是什么原因呢？

**Comment by ZhangGe6** [comment]
@Ryuk17 谢谢反馈。本地实验了一下，可以正常修改Sub op的initializer值并保存。请问在点击`download`后，终端是否出现异常的报错信息？

**Comment by ZhangGe6** [comment]
由于长时间没有得到回复，并且本地无法复现，本issue将关闭。如果问题仍然存在，欢迎reopen和继续讨论。
