### ISSUE TITLE
Support for conv node

### ISSUE THREAD

**Issue by MAhaitao999** [ZhangGe6/onnx-modifier#9]
添加conv这样的节点，weight和bias这样的参数是不支持赋值的，是否可以考虑添加一下Initializer节点以支持修改weight和bias这样的参数？

**Comment by ZhangGe6** [comment]
你好，添加含Initializer的节点已在计划中，但主要针对于含有一些简单参数的节点，比如`reshape` (节点`shape`值以Tensor的形式保存在图的initializer中)。

请问修改像是Conv节点的weight, bias这样复杂的参数，是碰到了实际的需求么？

**Comment by MAhaitao999** [comment]
> 你好，添加含Initializer的节点已在计划中，但主要针对一些含有简单参数的节点，比如`reshape` (节点`shape`值以Tensor的形式保存在图的initializer中)。
> 
> 请问修改像是Conv节点的weight, bias这样复杂的参数，是碰到了实际的需求么？

是的，有时需要添加一些特定参数的卷积操作来满足工程上的需求，比如说用具有特定参数的深度可分离卷积来模拟Identity恒等变换。

**Comment by ZhangGe6** [comment]
@MAhaitao999 哈喽你好，修改Initializer的功能（终于）开始支持了，详见[readme](https://github.com/ZhangGe6/onnx-modifier#edit-model-initializers)，支持编辑一些简单的参数（比如`Reshape`节点的`shape`值），也支持编辑一些复杂的参数（比如`Conv`节点的`weight`和`bias`）。欢迎使用，如果出现问题，欢迎继续交流~
