### ISSUE TITLE
launch from executable file的一个bug

### ISSUE THREAD

**Issue by Rickustc** [ZhangGe6/onnx-modifier#90]
通过launch from executable file方式部署的modifier，本地修改过后点击download之后，继续在修改后的模型上做修改就没法再次download了

**Comment by ZhangGe6** [comment]
@Rickustc 谢谢反馈。咦，我本地试了下，在一次download之后，是可以继续编辑并再次download的。

使用executable启动onnx-modifier，在打开编辑界面的同时，会启动一个终端，终端里会打印程序运行的log. 麻烦看一下log，是否有异常信息？另外，也存在一种可能：第二次download时，终端因为一些原因退出了，此时在编辑界面进行的编辑操作，就不会有任何响应了。

**Comment by Rickustc** [comment]
@ZhangGe6  感谢回复，应该是我开了代理的原因：D
