### ISSUE TITLE
静态节点的输入，转为动态batch的输入？现在支持吗？

### ISSUE THREAD

**Issue by sunliangpeng** [ZhangGe6/onnx-modifier#92]
静态节点的输入，转为动态batch的输入？现在支持吗？我修改这个初始值[3,560.26000]为[-1,560,26000]或者[batch,560,26000],不生效呢？保存不下来，求助

**Comment by ZhangGe6** [comment]
@sunliangpeng 请查看终端是否有异常报错信息？

**Comment by ZhangGe6** [comment]
@sunliangpeng 因长时间未得回复且本地无法复现，本issue将关闭。如果问题仍然存在，欢迎reopen和继续讨论。
