### ISSUE TITLE
支持给节点添加input

### ISSUE THREAD

**Issue by jerly-hjzhou** [ZhangGe6/onnx-modifier#93]
有这样一种需求就是我想删掉某个节点，这个节点往往是多输入的，比如concat，因此需要给被删除节点的子节点添加输入节点。但现在无法添加输入节点。

**Comment by ZhangGe6** [comment]
@jerly-hjzhou 谢谢反馈，该功能正在支持中。

**Comment by ZhangGe6** [comment]
@jerly-hjzhou 给节点/模型增加input的功能已开始支持，具体可参见: https://github.com/ZhangGe6/onnx-modifier?tab=readme-ov-file#add-new-model-inputs

欢迎使用和反馈问题~
