### ISSUE TITLE
求增加 npy文件上传参数的功能

### ISSUE THREAD

**Issue by wangjingg** [ZhangGe6/onnx-modifier#94]
参数可以直接下载为npy文件， 但上传文件时并不能直接上传npy，需要手动输入，很不方便。

**Comment by ZhangGe6** [comment]
@wangjingg 谢谢建议，这个功能正在尝试支持。

**Comment by ZhangGe6** [comment]
@wangjingg 已上传新版本，支持从numpy文件读取initializer数据。
![edit_initializer_from_npy](https://github.com/ZhangGe6/onnx-modifier/assets/63796752/b61b6cd8-0b29-4c27-89f0-26f77393c406)
