### ISSUE TITLE
无法添加LayerNormaliztion算子

### ISSUE THREAD

**Issue by Phoenix8215** [ZhangGe6/onnx-modifier#97]
## 问题描述
LayerNormaliztion算子无法正常添加，点击添加LayerNormaliztion算子会导致所有算子都无法添加
![demo1](https://github.com/ZhangGe6/onnx-modifier/assets/37546779/c6db862d-e52c-43f7-82b9-b8e95bf6a9d2)

感谢您提供如此🐂🍺的项目，期待您的回复🥰🥰🥰

**Comment by ZhangGe6** [comment]
@Phoenix8215 Hi, 谢谢反馈。LayerNormaliztion算子在opset >= 17后出现，请检查所编辑的模型的opset是否低于17。如果低于17，可重新导出opset>=17的ONNX模型，或使用[ONNX Version Converter](https://github.com/onnx/tutorials/blob/master/tutorials/VersionConversion.md)进行版本转换。

**Comment by Phoenix8215** [comment]
太谢谢啦，已经解决了，将opset设置成17就好了💞
